import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { ClinicalRecordAccessGrant } from '../../core/models/clinical-record.model';
import { ClinicalRecordsApiService } from '../../core/services/clinical-records-api.service';

@Component({ selector: 'app-health-record-sharing-detail-page', imports: [RouterLink], changeDetection: ChangeDetectionStrategy.OnPush,
template: `<main class="mx-auto max-w-4xl px-5 py-10 sm:px-8"><a routerLink="/me/health-records/sharing" class="font-bold text-brand-700 underline">← Manage sharing</a>@if (loading()) { <p role="status" class="mt-6 rounded-2xl border p-6">Loading access grant…</p> } @else if (error()) { <div role="alert" class="mt-6 rounded-2xl bg-red-50 p-6">This access grant is unavailable. <button type="button" (click)="load()" class="font-bold underline">Try again</button></div> } @else if (grant(); as g) { <h1 class="mt-6 text-3xl font-bold">Health record access</h1><section class="mt-6 rounded-2xl border bg-white p-6"><p class="mb-6 rounded-xl bg-slate-50 p-4">{{ statusMessage(g) }}</p><dl class="grid gap-5 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Provider</dt><dd class="font-bold">{{ g.provider.displayName }}</dd><dd class="text-sm text-slate-600">{{ g.provider.providerType }}</dd></div><div><dt class="text-sm text-slate-500">Status</dt><dd class="font-bold">{{ label(g.status) }}</dd></div><div><dt class="text-sm text-slate-500">Access</dt><dd>{{ scope(g) }}</dd></div>@if (g.recordType) { <div><dt class="text-sm text-slate-500">Record type</dt><dd>{{ label(g.recordType) }}</dd></div> }@if (g.clinicalRecord) { <div><dt class="text-sm text-slate-500">Clinical record</dt><dd>{{ g.clinicalRecord.title }}</dd><dd class="break-all text-sm text-slate-500">{{ g.clinicalRecord.reference }}</dd></div> }<div><dt class="text-sm text-slate-500">Granted</dt><dd>{{ date(g.grantedAt) }}</dd></div><div><dt class="text-sm text-slate-500">Expires</dt><dd>{{ g.expiresAt ? date(g.expiresAt) : 'No expiry' }}</dd></div>@if (g.revokedAt) { <div><dt class="text-sm text-slate-500">Revoked</dt><dd>{{ date(g.revokedAt) }}</dd></div> }</dl></section> } </main>` })
export class HealthRecordSharingDetailPageComponent { private readonly api=inject(ClinicalRecordsApiService); readonly reference=inject(ActivatedRoute).snapshot.paramMap.get('reference')??''; readonly grant=signal<ClinicalRecordAccessGrant|null>(null); readonly loading=signal(true); readonly error=signal(false); constructor(){this.load();} load(){this.loading.set(true);this.error.set(false);this.api.getAccessGrant(this.reference).pipe(finalize(()=>this.loading.set(false))).subscribe({next:g=>this.grant.set(g),error:()=>this.error.set(true)});} label(v:string){return v.split('_').map(x=>x[0]+x.slice(1).toLowerCase()).join(' ');} scope(g:ClinicalRecordAccessGrant){return g.scope==='ALL_RECORDS'?'All finalized health records':g.scope==='RECORD_TYPE'?`Finalized ${this.label(g.recordType ?? '')} records`:'One finalized health record';} statusMessage(g:ClinicalRecordAccessGrant){const access=this.scope(g).toLowerCase();if(g.status==='REVOKED')return `This access was revoked on ${this.date(g.revokedAt!)}. Previous access history remains available.`;if(g.status==='EXPIRED')return `This access expired on ${this.date(g.expiresAt!)}.`;return g.expiresAt?`${g.provider.displayName} can access your ${access} until ${this.date(g.expiresAt)}.`:`${g.provider.displayName} can access your ${access} until you revoke this permission.`;} date(v:string){return new Intl.DateTimeFormat('en-NG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));} }
