import { TestBed } from '@angular/core/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { of } from 'rxjs';
import { ClinicalRecordsApiService } from '../../core/services/clinical-records-api.service';
import { HealthRecordDetailPageComponent } from './health-record-detail-page.component';
import { record } from './health-records-page.component.spec';
describe('HealthRecordDetailPageComponent', () => {
  async function setup(value = record()) { const api = { getMine: vi.fn(() => of(value)), getPatientAttachmentAccess: vi.fn(() => of({ url: 'https://files.example.test/image', expiresAt: '2026-08-29T11:00:00Z' })) }; await TestBed.configureTestingModule({ imports: [HealthRecordDetailPageComponent], providers: [provideRouter([]), { provide: ActivatedRoute, useValue: { snapshot: { paramMap: { get: () => 'SC-CLR-ABC' } } } }, { provide: ClinicalRecordsApiService, useValue: api }] }).compileComponents(); const fixture = TestBed.createComponent(HealthRecordDetailPageComponent); fixture.detectChanges(); return { fixture, api }; }
  it('renders finalized consultation detail read-only', async () => { const { fixture } = await setup(); const text = fixture.nativeElement.textContent; expect(text).toContain('Presenting complaint'); expect(text).toContain('Pain'); expect(text).toContain('Diagnosis'); expect(fixture.nativeElement.querySelector('textarea')).toBeNull(); });
  it('renders patient attachment metadata without upload or delete controls', async () => { const value = { ...record(), attachments: [attachment()] }; const { fixture, api } = await setup(value); const text = fixture.nativeElement.textContent; expect(text).toContain('report.png'); expect(text).toContain('1 MB'); expect(text).not.toContain('Upload file'); expect(text).not.toContain('Delete'); expect(api.getPatientAttachmentAccess).not.toHaveBeenCalled(); });
  it('uses patient authorized access on demand and clears image preview state', async () => { const value = { ...record(), attachments: [attachment()] }; const { fixture, api } = await setup(value); const c = fixture.componentInstance; expect(c.previewUrl()).toBeNull(); c.viewAttachment(attachment()); expect(api.getPatientAttachmentAccess).toHaveBeenCalledWith('SC-CLR-ABC', 'SC-CLA-2'); expect(c.previewUrl()).toBe('https://files.example.test/image'); fixture.detectChanges(); expect(fixture.nativeElement.querySelector('[role="dialog"]')).not.toBeNull(); c.closePreview(); expect(c.previewUrl()).toBeNull(); });
  it('renders the finalized empty attachment state', async () => { const { fixture } = await setup(); expect(fixture.nativeElement.textContent).toContain('No supporting files were included'); });
});
function attachment() { return { reference: 'SC-CLA-2', originalName: 'report.png', mimeType: 'image/png', sizeBytes: 1048576, resourceType: 'IMAGE' as const, createdAt: '2026-08-29T10:30:00Z' }; }
