import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { ClinicalRecordAccessGrant } from '../../core/models/clinical-record.model';
import { ClinicalRecordsApiService } from '../../core/services/clinical-records-api.service';

@Component({
  selector: 'app-health-record-sharing-page', imports: [RouterLink], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<main class="mx-auto max-w-7xl px-5 py-10 sm:px-8">
    <a routerLink="/me/health-records" class="font-bold text-brand-700 underline">← Health Records</a>
    <div class="mt-5 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-3xl font-bold">Manage sharing</h1><p class="mt-2 text-slate-600">You control which providers can view your health records. Access can be revoked at any time.</p></div><div class="flex flex-wrap gap-3"><a routerLink="/me/health-records/access-history" class="rounded-xl border px-4 py-3 font-bold">Access history</a><a routerLink="/me/health-records/sharing/new" class="rounded-xl bg-brand-700 px-4 py-3 font-bold text-white">Share health records</a></div></div>
    @if (loading()) { <p role="status" class="mt-8 rounded-2xl border bg-white p-6">Loading sharing settings…</p> }
    @else if (error()) { <div role="alert" class="mt-8 rounded-2xl bg-red-50 p-6">We couldn't load your sharing settings. <button type="button" (click)="load()" class="font-bold underline">Try again</button></div> }
    @else if (!grants().length) { <section class="mt-8 rounded-2xl border bg-white p-8 text-center"><h2 class="text-xl font-bold">No health record access has been shared</h2><p class="mt-2 text-slate-600">Providers will only see records you explicitly authorize.</p><a routerLink="/me/health-records/sharing/new" class="mt-5 inline-flex rounded-xl bg-brand-700 px-5 py-3 font-bold text-white">Share health records</a></section> }
    @else { <div class="mt-8 overflow-x-auto rounded-2xl border bg-white"><table class="min-w-full divide-y"><thead class="bg-slate-50"><tr>@for (heading of ['Provider','Scope','Access','Granted','Expires','Status','Action']; track heading) { <th class="px-5 py-4 text-left text-xs font-bold uppercase text-slate-500">{{ heading }}</th> }</tr></thead><tbody class="divide-y">@for (grant of grants(); track grant.reference) { <tr><td class="px-5 py-4 font-bold">{{ grant.provider.displayName }}</td><td class="px-5 py-4">{{ scopeLabel(grant) }}</td><td class="px-5 py-4">{{ accessLabel(grant) }}</td><td class="px-5 py-4">{{ date(grant.grantedAt) }}</td><td class="px-5 py-4">{{ grant.expiresAt ? date(grant.expiresAt) : 'No expiry' }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-3 py-1 text-sm font-bold">{{ statusLabel(grant.status) }}</span></td><td class="px-5 py-4"><div class="flex gap-3"><a [routerLink]="['/me/health-records/sharing', grant.reference]" class="rounded-lg border px-3 py-2 font-bold text-brand-700">View</a>@if (grant.status === 'ACTIVE') { <button type="button" (click)="openRevoke(grant)" class="rounded-lg border border-red-200 px-3 py-2 font-bold text-red-700">Revoke</button> }</div></td></tr> }</tbody></table></div>@if (totalPages() > 1) { <nav aria-label="Sharing grants pages" class="mt-5 flex items-center justify-between"><button type="button" (click)="goTo(page()-1)" [disabled]="page() <= 1" class="rounded-xl border px-4 py-2 font-bold disabled:opacity-50">Previous</button><span>Page {{ page() }} of {{ totalPages() }}</span><button type="button" (click)="goTo(page()+1)" [disabled]="page() >= totalPages()" class="rounded-xl border px-4 py-2 font-bold disabled:opacity-50">Next</button></nav> } }
    @if (mutationError()) { <p role="alert" class="mt-4 rounded-xl bg-red-50 p-4 text-red-900">{{ mutationError() }}</p> }
    @if (revokeTarget(); as grant) { <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="alertdialog" aria-modal="true" aria-labelledby="revoke-sharing-title" class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 id="revoke-sharing-title" class="text-2xl font-bold">Revoke access?</h2><p class="mt-3 text-slate-700">{{ grant.provider.displayName }} will no longer be able to access your health records through this sharing permission. Previous access history will remain available.</p><div class="mt-6 flex justify-end gap-3"><button type="button" (click)="cancelRevoke()" [disabled]="revoking() !== null" class="rounded-lg border px-4 py-2 font-bold">Cancel</button><button type="button" (click)="confirmRevoke()" [disabled]="revoking() !== null" class="rounded-lg bg-red-700 px-4 py-2 font-bold text-white disabled:opacity-50">{{ revoking() ? 'Revoking…' : 'Revoke access' }}</button></div></section></div> }
  </main>`,
})
export class HealthRecordSharingPageComponent {
  private readonly api = inject(ClinicalRecordsApiService); readonly grants = signal<readonly ClinicalRecordAccessGrant[]>([]); readonly loading = signal(true); readonly error = signal(false); readonly page = signal(1); readonly totalPages = signal(0); readonly revokeTarget = signal<ClinicalRecordAccessGrant | null>(null); readonly revoking = signal<string | null>(null); readonly mutationError = signal('');
  constructor() { this.load(); }
  load(): void { this.loading.set(true); this.error.set(false); this.api.listAccessGrants(this.page()).pipe(finalize(() => this.loading.set(false))).subscribe({ next: p => { this.grants.set(p.items); this.totalPages.set(p.totalPages ?? 0); }, error: () => this.error.set(true) }); }
  goTo(page: number): void { if (page < 1 || (this.totalPages() && page > this.totalPages())) return; this.page.set(page); this.load(); }
  openRevoke(grant: ClinicalRecordAccessGrant): void { if (grant.status === 'ACTIVE' && !this.revoking()) this.revokeTarget.set(grant); }
  cancelRevoke(): void { if (!this.revoking()) this.revokeTarget.set(null); }
  confirmRevoke(): void { const grant = this.revokeTarget(); if (!grant || grant.status !== 'ACTIVE' || this.revoking()) return; this.revoking.set(grant.reference); this.mutationError.set(''); this.api.revokeAccessGrant(grant.reference).pipe(finalize(() => this.revoking.set(null))).subscribe({ next: revoked => { this.grants.update(items => items.map(item => item.reference === revoked.reference ? revoked : item)); this.revokeTarget.set(null); }, error: () => this.mutationError.set('Unable to revoke access. Please refresh and try again.') }); }
  scopeLabel(g: ClinicalRecordAccessGrant): string { return g.scope === 'HEALTH_PASSPORT' ? 'Health Passport' : g.scope === 'ALL_RECORDS' ? 'All health records' : g.scope === 'RECORD_TYPE' ? 'Record type' : 'Single record'; }
  accessLabel(g: ClinicalRecordAccessGrant): string { return g.scope === 'HEALTH_PASSPORT' ? 'Shareable Health Passport only' : g.scope === 'ALL_RECORDS' ? 'Health Passport + finalized clinical records' : g.scope === 'RECORD_TYPE' ? `${this.typeLabel(g.recordType)} records` : g.clinicalRecord?.title ?? 'Selected health record'; }
  statusLabel(v: string): string { return v[0] + v.slice(1).toLowerCase(); }
  typeLabel(v: string | null): string { return v ? v.split('_').map(x => x[0] + x.slice(1).toLowerCase()).join(' ') : '—'; }
  date(v: string): string { return new Intl.DateTimeFormat('en-NG', { dateStyle: 'medium' }).format(new Date(v)); }
}
