import { CommonModule } from '@angular/common';import { Component,computed,inject,signal } from '@angular/core';import { FormsModule } from '@angular/forms';import { Router,RouterLink } from '@angular/router';import { InstitutionalCareApiService } from '../../core/services/institutional-care-api.service';import { InstitutionalCareSummary } from '../../core/models/institutional-care.model';
@Component({selector:'app-institutional-care-page',standalone:true,imports:[CommonModule,FormsModule,RouterLink],template:`
<section class="mx-auto max-w-5xl space-y-6 p-4 md:p-8">
 <header><a routerLink="/me/request-care" class="text-sm font-bold text-brand-700">← See a Doctor</a><h1 class="mt-3 text-3xl font-black text-slate-950">Choose a hospital or clinic</h1><p class="mt-2 max-w-2xl text-slate-600">Start with the institution you trust. SmartClinic will show only the ways that institution can care for you.</p></header>
 <label class="block"><span class="font-bold">Search hospitals and clinics</span><div class="mt-2 flex gap-2"><input [(ngModel)]="query" (keyup.enter)="load()" class="min-h-12 flex-1 rounded-xl border px-4" placeholder="Hospital or clinic name"/><button (click)="load()" class="rounded-xl bg-slate-950 px-5 font-bold text-white">Search</button></div></label>
 @if(loading()){<p class="rounded-2xl bg-slate-50 p-5">Finding participating institutions…</p>}
 @if(!loading()&&!items().length){<div class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-black">No participating institution found</h2><p class="mt-2 text-slate-600">You can still ask SmartClinic to find a doctor for you.</p><a routerLink="/me/request-care" class="mt-4 inline-block rounded-xl bg-brand-700 px-5 py-3 font-bold text-white">Find a doctor instead</a></div>}
 <div class="grid gap-4 md:grid-cols-2">@for(item of items();track item.providerReference){<button type="button" (click)="open(item)" class="rounded-2xl border bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5"><h2 class="text-xl font-black">{{item.displayName}}</h2><p class="mt-1 text-sm text-slate-500">{{place(item)}}</p><div class="mt-4 flex flex-wrap gap-2">@if(item.capabilities.virtual){<span class="rounded-full bg-violet-50 px-3 py-1 text-sm font-bold text-violet-800">Online care</span>}@if(item.capabilities.inPerson){<span class="rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-800">In person</span>}@if(item.capabilities.homeVisit){<span class="rounded-full bg-amber-50 px-3 py-1 text-sm font-bold text-amber-800">Home care</span>}</div><p class="mt-4 font-bold text-brand-700">View care options →</p></button>}</div>
</section>`})
export class InstitutionalCarePageComponent{private readonly api=inject(InstitutionalCareApiService);private readonly router=inject(Router);readonly items=signal<readonly InstitutionalCareSummary[]>([]);readonly loading=signal(false);query='';constructor(){this.load();}load(){this.loading.set(true);this.api.list(this.query).subscribe({next:v=>{this.items.set(v);this.loading.set(false)},error:()=>this.loading.set(false)});}open(i:InstitutionalCareSummary){void this.router.navigate(['/me/institutions',i.providerReference]);}place(i:InstitutionalCareSummary){return [i.location.city,i.location.stateOrRegion,i.location.countryCode].filter(Boolean).join(', ')||'SmartClinic Network';}}