import { CommonModule } from '@angular/common';import { Component,inject,signal } from '@angular/core';import { ActivatedRoute,Router,RouterLink } from '@angular/router';import { InstitutionalCareDetail,InstitutionalCarePath } from '../../core/models/institutional-care.model';import { InstitutionalCareApiService } from '../../core/services/institutional-care-api.service';
@Component({selector:'app-institutional-care-detail-page',standalone:true,imports:[CommonModule,RouterLink],template:`
<section class="mx-auto max-w-4xl space-y-6 p-4 md:p-8">@if(item();as i){<header><a routerLink="/me/institutions" class="text-sm font-bold text-brand-700">← Hospitals & clinics</a><h1 class="mt-3 text-3xl font-black">{{i.displayName}}</h1><p class="mt-2 text-slate-600">Choose what you need. You will not be asked to choose the same delivery method again.</p></header>
<div class="grid gap-4 md:grid-cols-2">
 @if(i.capabilities.virtual){<button (click)="choose('VIRTUAL_NOW')" class="rounded-2xl border bg-white p-5 text-left"><h2 class="text-xl font-black">Talk to a doctor online</h2><p class="mt-2 text-slate-600">Send a request to an eligible doctor in this institution's virtual clinic.</p><p class="mt-4 font-bold text-brand-700">Start online care →</p></button>
 <button (click)="choose('VIRTUAL_LATER')" class="rounded-2xl border bg-white p-5 text-left"><h2 class="text-xl font-black">Book an online appointment</h2><p class="mt-2 text-slate-600">Choose a future date and time with this institution.</p><p class="mt-4 font-bold text-brand-700">Book for later →</p></button>}
 @if(i.capabilities.inPerson){<button (click)="choose('IN_PERSON')" class="rounded-2xl border bg-white p-5 text-left"><h2 class="text-xl font-black">Visit in person</h2><p class="mt-2 text-slate-600">Continue with the hospital or clinic's physical-care services and locations.</p><p class="mt-4 font-bold text-brand-700">Choose in-person care →</p></button>}
 @if(i.capabilities.homeVisit){<button (click)="choose('HOME_VISIT')" class="rounded-2xl border bg-white p-5 text-left"><h2 class="text-xl font-black">Care at home</h2><p class="mt-2 text-slate-600">Use this institution's home-care service where available.</p><p class="mt-4 font-bold text-brand-700">Check home care →</p></button>}
</div>
@if(i.capabilities.virtual&&i.virtualDoctors.length){<div class="rounded-2xl bg-slate-50 p-5"><h2 class="text-lg font-black">Virtual clinic team</h2><p class="mt-1 text-sm text-slate-600">Approved clinicians affiliated with {{i.displayName}}.</p><div class="mt-3 grid gap-2 md:grid-cols-2">@for(d of i.virtualDoctors;track d.providerReference){<div class="rounded-xl bg-white p-4"><p class="font-bold">{{d.displayName}}</p>@if(d.isDefault){<p class="text-xs font-bold text-brand-700">Preferred virtual clinician</p>}</div>}</div></div>}
@if(!i.capabilities.virtual&&!i.capabilities.inPerson&&!i.capabilities.homeVisit){<div class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-black">Care options are being configured</h2><p class="mt-2 text-slate-600">You do not need to wait. SmartClinic can find another eligible provider.</p><a routerLink="/me/request-care" class="mt-4 inline-block font-bold text-brand-700">Find another provider →</a></div>}
}</section>`})
export class InstitutionalCareDetailPageComponent{private readonly api=inject(InstitutionalCareApiService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);readonly item=signal<InstitutionalCareDetail|null>(null);constructor(){this.api.detail(this.route.snapshot.paramMap.get('reference')!).subscribe(v=>this.item.set(v));}choose(path:InstitutionalCarePath){const i=this.item();if(!i)return;const doctorMode=path==='VIRTUAL_NOW'?'NOW':path==='VIRTUAL_LATER'?'LATER':path==='IN_PERSON'?'HOSPITAL':'';void this.router.navigate(['/me/request-care'],{queryParams:{institution:i.providerReference,doctorMode,deliveryMode:path==='IN_PERSON'?'IN_PERSON':path==='HOME_VISIT'?'HOME_VISIT':'VIRTUAL'}});}}