import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { ClinicalRecord, ClinicalRecordAccessProvider, ClinicalRecordAccessScope, ClinicalRecordType, CreateClinicalRecordAccessGrantRequest } from '../../core/models/clinical-record.model';
import { ClinicalRecordsApiService } from '../../core/services/clinical-records-api.service';

@Component({
  selector: 'app-new-health-record-sharing-page', imports: [ReactiveFormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<main class="mx-auto max-w-4xl px-5 py-10 sm:px-8"><a routerLink="/me/health-records/sharing" class="font-bold text-brand-700 underline">← Manage sharing</a><h1 class="mt-5 text-3xl font-bold">Share health records</h1><p class="mt-2 text-slate-600">Give a connected provider read-only access to finalized Clinical Records. Only providers with an active connection appear here.</p><a routerLink="/me/providers/connect" [queryParams]="{ returnUrl: '/me/health-records/sharing/new' }" class="mt-3 inline-block font-bold text-brand-700 underline">Connect with another provider</a>
  @if (recordsLoading()) { <p role="status" class="mt-8 rounded-2xl border p-6">Loading your health records…</p> }
  @else if (recordsError()) { <div role="alert" class="mt-8 rounded-2xl bg-red-50 p-6">We couldn't prepare sharing. <button type="button" (click)="loadRecords()" class="font-bold underline">Try again</button></div> }
  @else { <form [formGroup]="form" (ngSubmit)="submit()" class="mt-8 grid gap-6 rounded-2xl border bg-white p-6">
    <section><h2 class="font-bold">Provider</h2><div class="mt-3 flex flex-col gap-3 sm:flex-row"><label class="flex-1"><span class="sr-only">Search providers</span><input [formControl]="providerSearch" maxlength="120" placeholder="Search providers by name" class="min-h-12 w-full rounded-xl border px-3 py-3"></label><button type="button" (click)="searchProviders()" [disabled]="providerLoading()" class="rounded-xl border border-brand-700 px-5 py-3 font-bold text-brand-700">{{ providerLoading() ? 'Searching…' : 'Search' }}</button></div>
      @if (selectedProvider(); as selected) { <div class="mt-4 rounded-xl border-2 border-brand-600 bg-brand-50 p-4"><p class="text-xs font-bold uppercase text-brand-700">Selected provider</p><p class="mt-1 font-bold">{{ selected.displayName }}</p><p class="text-sm text-slate-600">{{ selected.providerType }}{{ locationLabel(selected) ? ' · ' + locationLabel(selected) : '' }}</p><button type="button" (click)="clearProvider()" class="mt-2 font-bold text-brand-700 underline">Change provider</button></div> }
      @if (providerLoading()) { <p role="status" class="mt-4 text-slate-600">Loading providers…</p> }
      @else if (providerError()) { <div role="alert" class="mt-4 rounded-xl bg-red-50 p-4">Unable to load providers. <button type="button" (click)="loadProviders(providerPage())" class="font-bold underline">Try again</button></div> }
      @else if (!providers().length) { <p class="mt-4 rounded-xl bg-slate-50 p-4 text-slate-600">No providers match this search.</p> }
      @else { <div class="mt-4 grid gap-3">@for (provider of providers(); track provider.providerReference) { <button type="button" (click)="selectProvider(provider)" [attr.aria-pressed]="form.controls.providerReference.value === provider.providerReference" class="rounded-xl border p-4 text-left hover:border-brand-600"><span class="block font-bold">{{ provider.displayName }}</span><span class="mt-1 block text-sm text-slate-600">{{ provider.providerType }}{{ locationLabel(provider) ? ' · ' + locationLabel(provider) : '' }}</span></button> }</div>
        <div class="mt-4 flex items-center justify-between gap-3"><button type="button" (click)="loadProviders(providerPage() - 1)" [disabled]="providerPage() <= 1 || providerLoading()" class="rounded-lg border px-3 py-2 font-bold">Previous</button><span class="text-sm">Page {{ providerPage() }} of {{ providerTotalPages() || 1 }}</span><button type="button" (click)="loadProviders(providerPage() + 1)" [disabled]="providerPage() >= providerTotalPages() || providerLoading()" class="rounded-lg border px-3 py-2 font-bold">Next</button></div> }
    </section>
    <fieldset class="grid gap-3"><legend class="font-bold">Access</legend><label class="flex gap-3"><input type="radio" formControlName="scope" value="ALL_RECORDS"> Share all finalized health records</label><label class="flex gap-3"><input type="radio" formControlName="scope" value="RECORD_TYPE"> Share records of one type</label><label class="flex gap-3"><input type="radio" formControlName="scope" value="SINGLE_RECORD"> Share one health record</label></fieldset>
    @if (form.controls.scope.value === 'RECORD_TYPE') { <label class="grid gap-2 font-bold">Record type<select formControlName="recordType" class="rounded-xl border px-3 py-3"><option value="">Select type</option>@for (type of recordTypes; track type) { <option [value]="type">{{ label(type) }}</option> }</select></label> }
    @if (form.controls.scope.value === 'SINGLE_RECORD') { <label class="grid gap-2 font-bold">Finalized health record<select formControlName="clinicalRecordReference" class="rounded-xl border px-3 py-3"><option value="">Select record</option>@for (record of records(); track record.reference) { <option [value]="record.reference">{{ record.title }} — {{ label(record.recordType) }}</option> }</select></label> }
    <label class="grid gap-2 font-bold">Expiry <span class="text-sm font-normal text-slate-500">Optional</span><input type="date" formControlName="expiresOn" class="rounded-xl border px-3 py-3"></label>
    <section class="rounded-xl bg-slate-50 p-5"><h2 class="font-bold">Review</h2><dl class="mt-3 grid gap-2"><div><dt class="inline font-bold">Share with: </dt><dd class="inline">{{ selectedProvider()?.displayName || 'Select a provider' }}</dd></div><div><dt class="inline font-bold">Access: </dt><dd class="inline">{{ reviewAccess() }}</dd></div><div><dt class="inline font-bold">Duration: </dt><dd class="inline">{{ form.controls.expiresOn.value ? 'Until ' + dateOnly(form.controls.expiresOn.value) : 'No expiry' }}</dd></div></dl><p class="mt-3 text-sm text-slate-600">The provider receives read-only access to the covered finalized Clinical Records.</p></section>
    @if (error()) { <p role="alert" class="rounded-xl bg-red-50 p-4 text-red-900">{{ error() }}</p> }<button type="submit" [disabled]="saving()" class="rounded-xl bg-brand-700 px-5 py-3 font-bold text-white disabled:opacity-50">{{ saving() ? 'Sharing…' : 'Share health records' }}</button>
  </form> }</main>`,
})
export class NewHealthRecordSharingPageComponent {
  private readonly api = inject(ClinicalRecordsApiService); private readonly router = inject(Router); private readonly route = inject(ActivatedRoute);
  readonly providers = signal<readonly ClinicalRecordAccessProvider[]>([]); readonly selectedProvider = signal<ClinicalRecordAccessProvider | null>(null); readonly providerSearch = new FormControl('', { nonNullable: true }); readonly providerLoading = signal(false); readonly providerError = signal(false); readonly providerPage = signal(1); readonly providerTotalPages = signal(0);
  readonly records = signal<readonly ClinicalRecord[]>([]); readonly recordsLoading = signal(true); readonly recordsError = signal(false); readonly saving = signal(false); readonly error = signal(''); readonly recordTypes: readonly ClinicalRecordType[] = ['CONSULTATION', 'LAB_RESULT', 'IMAGING_RESULT', 'PROCEDURE', 'PHARMACY', 'FOLLOW_UP', 'OTHER'];
  readonly form = new FormGroup({ providerReference: new FormControl('', { nonNullable: true, validators: [Validators.required] }), scope: new FormControl<ClinicalRecordAccessScope>('ALL_RECORDS', { nonNullable: true }), recordType: new FormControl<ClinicalRecordType | ''>('', { nonNullable: true }), clinicalRecordReference: new FormControl('', { nonNullable: true }), expiresOn: new FormControl('', { nonNullable: true }) });
  constructor() { this.loadRecords(); this.loadProviders(1); }
  loadRecords() { this.recordsLoading.set(true); this.recordsError.set(false); this.api.listMine(1, 100).pipe(finalize(() => this.recordsLoading.set(false))).subscribe({ next: page => { this.records.set(page.items); const selected = this.route.snapshot.queryParamMap.get('recordReference'); if (selected && page.items.some(record => record.reference === selected)) this.form.patchValue({ scope: 'SINGLE_RECORD', clinicalRecordReference: selected }); }, error: () => this.recordsError.set(true) }); }
  searchProviders() { this.loadProviders(1); }
  loadProviders(page: number) { if (page < 1 || this.providerLoading()) return; this.providerLoading.set(true); this.providerError.set(false); this.api.searchAccessProviders(this.providerSearch.value, page, 10).pipe(finalize(() => this.providerLoading.set(false))).subscribe({ next: result => { this.providers.set(result.items); this.providerPage.set(result.page); this.providerTotalPages.set(result.totalPages); }, error: () => { this.providers.set([]); this.providerError.set(true); } }); }
  selectProvider(provider: ClinicalRecordAccessProvider) { this.selectedProvider.set(provider); this.form.controls.providerReference.setValue(provider.providerReference); }
  clearProvider() { this.selectedProvider.set(null); this.form.controls.providerReference.setValue(''); }
  submit() { this.error.set(''); const scope = this.form.controls.scope.value; if (this.form.invalid || (scope === 'RECORD_TYPE' && !this.form.controls.recordType.value) || (scope === 'SINGLE_RECORD' && !this.form.controls.clinicalRecordReference.value)) { this.form.markAllAsTouched(); this.error.set('Choose a provider and complete the access details.'); return; } const body: CreateClinicalRecordAccessGrantRequest = { providerReference: this.form.controls.providerReference.value, scope, ...(scope === 'RECORD_TYPE' ? { recordType: this.form.controls.recordType.value as ClinicalRecordType } : {}), ...(scope === 'SINGLE_RECORD' ? { clinicalRecordReference: this.form.controls.clinicalRecordReference.value } : {}), ...(this.form.controls.expiresOn.value ? { expiresAt: new Date(`${this.form.controls.expiresOn.value}T23:59:59.999Z`).toISOString() } : {}) }; this.saving.set(true); this.api.createAccessGrant(body).pipe(finalize(() => this.saving.set(false))).subscribe({ next: grant => this.router.navigate(['/me/health-records/sharing', grant.reference]), error: () => this.error.set('Unable to share these health records. Review the details and try again.') }); }
  reviewAccess() { const scope = this.form.controls.scope.value; if (scope === 'ALL_RECORDS') return 'All finalized health records'; if (scope === 'RECORD_TYPE') return this.form.controls.recordType.value ? `${this.label(this.form.controls.recordType.value)} records` : 'Select a record type'; return this.records().find(record => record.reference === this.form.controls.clinicalRecordReference.value)?.title ?? 'Select a health record'; }
  locationLabel(provider: ClinicalRecordAccessProvider) { return [provider.location.city, provider.location.stateOrRegion, provider.location.countryCode].filter(Boolean).join(', '); }
  label(value: string) { return value.split('_').map(part => part[0] + part.slice(1).toLowerCase()).join(' '); }
  dateOnly(value: string) { return new Intl.DateTimeFormat('en-NG', { dateStyle: 'long' }).format(new Date(`${value}T12:00:00Z`)); }
}
