import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { finalize } from 'rxjs';
import { ClinicalOrder, ClinicalOrderType, FulfillmentDirectoryItem, PatientOrderFulfillment } from '../../core/models/pharmacy-fulfillment.model';
import { PharmacyFulfillmentApiService } from '../../core/services/pharmacy-fulfillment-api.service';

@Component({selector:'app-patient-orders-page',imports:[RouterLink],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<main class="mx-auto max-w-6xl px-5 py-8 sm:px-8"><header class="rounded-[2rem] border bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[.2em] text-brand-700">My Care</p><h1 class="mt-2 text-3xl font-bold">Tests & referrals</h1><p class="mt-2 text-slate-600">Requests from your care team. Choose a connected laboratory or imaging centre where needed.</p></header>
@if(loading()){<p role="status" class="mt-6 rounded-xl border p-5">Loading your care orders…</p>} @else if(error()){<p role="alert" class="mt-6 rounded-xl bg-red-50 p-5">We couldn't load your tests and referrals. <button (click)="load()" class="font-bold underline">Try again</button></p>} @else if(!items().length){<section class="mt-6 rounded-2xl border bg-white p-8 text-center"><h2 class="text-xl font-bold">Nothing waiting for you</h2><p class="mt-2 text-slate-600">New laboratory, imaging and referral requests will appear here.</p></section>} @else {<div class="mt-6 grid gap-4">@for(o of items();track o.reference){<a [routerLink]="['/me/orders',o.reference]" class="rounded-2xl border bg-white p-5 shadow-sm"><div class="flex items-start justify-between gap-4"><div><p class="font-bold text-brand-800">{{label(o.type)}}</p><h2 class="mt-1 text-lg font-bold">{{o.clinicalNote || 'Clinical request'}}</h2><p class="mt-2 text-sm text-slate-600">From {{o.orderingProvider.displayName}} · {{date(o.issuedAt)}}</p></div><span class="rounded-full bg-brand-50 px-3 py-1 text-xs font-bold text-brand-800">{{o.fulfillment?.status || 'ACTION NEEDED'}}</span></div><p class="mt-4 font-bold text-brand-700">Open →</p></a> }</div> }</main>`})
export class PatientOrdersPageComponent{private api=inject(PharmacyFulfillmentApiService);readonly loading=signal(true);readonly error=signal(false);readonly items=signal<readonly ClinicalOrder[]>([]);constructor(){this.load()}load(){this.loading.set(true);this.error.set(false);Promise.all(['LABORATORY','IMAGING','REFERRAL','PROCEDURE'].map(t=>new Promise<ClinicalOrder[]>((resolve,reject)=>this.api.listPatientOrdersByType(t as any,1,50).subscribe({next:p=>resolve([...p.items]),error:reject})))).then(x=>this.items.set(x.flat().sort((a,b)=>(b.issuedAt||b.createdAt).localeCompare(a.issuedAt||a.createdAt)))).catch(()=>this.error.set(true)).finally(()=>this.loading.set(false))}label(t:ClinicalOrderType){return ({LABORATORY:'Laboratory test',IMAGING:'Imaging',REFERRAL:'Referral',PROCEDURE:'Procedure / follow-up'} as any)[t]||t}date(v:string|null){return v?new Intl.DateTimeFormat('en-NG',{dateStyle:'medium'}).format(new Date(v)):'—'}}
