import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AdminProviderEarning, ProviderEarning, ProviderEarningCurrencySummary, ProviderEarningSourceType, ProviderEarningStatus } from '../../core/models/provider-earning.model';
import { ProviderEarningsApiService } from '../../core/services/provider-earnings-api.service';
import { earningSourceLabel, earningStatusLabel, formatEarningMoney } from './provider-earning-presentation';
@Component({ selector: 'app-earnings-page', imports: [ReactiveFormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush,
template: `<main class="mx-auto max-w-7xl px-5 py-10 sm:px-8"><header><p class="text-sm font-bold uppercase tracking-wider text-brand-600">{{ admin ? 'Operations' : 'Provider workspace' }}</p><h1 class="mt-2 text-3xl font-bold">{{ admin ? 'Revenue' : 'Earnings' }}</h1><p class="mt-2 text-slate-600">{{ admin ? 'Platform commission and provider earnings recorded across SmartClinic services.' : 'Review your Provider share and the transactions that produced it.' }}</p></header>
@if(initialLoading()){<p role="status" class="mt-8 rounded-2xl border bg-white p-6">Loading financial summary…</p>}@else{
@if(summaryError()){<div role="alert" class="mt-8 rounded-2xl bg-red-50 p-5">Financial summary is unavailable. <button type="button" (click)="load()" class="font-bold underline">Try again</button></div>}@else if(!summaries().length){<p class="mt-8 rounded-2xl border bg-white p-6">No earnings recorded yet. Earnings will appear here as eligible SmartClinic services progress through their financial lifecycle.</p>}@else{@for(s of summaries();track s.currency){<section class="mt-8 rounded-2xl border bg-white p-6"><div class="flex flex-wrap justify-between gap-3"><div><h2 class="text-2xl font-bold">{{s.currency}}</h2><p class="text-sm text-slate-600">{{s.earningCount}} transaction{{s.earningCount===1?'':'s'}}</p></div><div><p class="text-sm text-slate-600">{{admin?'Gross Transaction Value':'Provider Share'}}</p><p class="text-3xl font-bold">{{money(admin?s.grossAmountMinor:s.providerShareMinor,s.currency)}}</p></div></div>
<div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@if(admin){<article class="rounded-xl bg-slate-50 p-4"><p>Platform Commission</p><strong>{{money(s.commissionAmountMinor,s.currency)}}</strong></article><article class="rounded-xl bg-slate-50 p-4"><p>Provider Share</p><strong>{{money(s.providerShareMinor,s.currency)}}</strong></article>}<article class="rounded-xl bg-amber-50 p-4"><p class="font-semibold">Held</p><strong>{{money(s.heldAmountMinor,s.currency)}}</strong><p class="text-xs">Not yet available for payout.</p></article><article class="rounded-xl bg-blue-50 p-4"><p class="font-semibold">Payable</p><strong>{{money(s.payableAmountMinor,s.currency)}}</strong><p class="text-xs">Earned and awaiting settlement.</p></article><article class="rounded-xl bg-green-50 p-4"><p class="font-semibold">Settled</p><strong>{{money(s.settledAmountMinor,s.currency)}}</strong><p class="text-xs">Already settled.</p></article>@if(s.voidedAmountMinor>0){<article class="rounded-xl bg-slate-100 p-4"><p class="font-semibold">Voided</p><strong>{{money(s.voidedAmountMinor,s.currency)}}</strong></article>}</div>
<h3 class="mt-6 text-lg font-bold">By source</h3><div class="mt-3 overflow-x-auto"><table class="min-w-[620px] w-full text-left"><thead><tr><th class="p-3">Source</th><th class="p-3">Count</th><th class="p-3">Gross</th><th class="p-3">{{admin?'Platform commission':'Commission'}}</th><th class="p-3">Provider share</th></tr></thead><tbody>@for(b of s.sourceBreakdown;track b.key){<tr class="border-t"><td class="p-3">{{source(b.key)}}</td><td class="p-3">{{b.earningCount}}</td><td class="p-3">{{money(b.grossAmountMinor,s.currency)}}</td><td class="p-3">{{money(b.commissionAmountMinor,s.currency)}}</td><td class="p-3">{{money(b.providerShareMinor,s.currency)}}</td></tr>}</tbody></table></div></section>}}
<section class="mt-8"><h2 class="text-2xl font-bold">Transaction history</h2><form [formGroup]="filters" (ngSubmit)="apply()" class="mt-4 grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2 lg:grid-cols-6">@if(admin){<label class="font-semibold">Provider reference<input formControlName="providerReference" placeholder="e.g. SCPR-..." class="mt-1 min-h-11 w-full rounded-lg border px-3"></label>}<label class="font-semibold">Status<select formControlName="status" class="mt-1 min-h-11 w-full rounded-lg border px-3"><option value="">All statuses</option>@for(v of statuses;track v){<option [value]="v">{{status(v)}}</option>}</select></label><label class="font-semibold">Source<select formControlName="sourceType" class="mt-1 min-h-11 w-full rounded-lg border px-3"><option value="">All sources</option>@for(v of sources;track v){<option [value]="v">{{source(v)}}</option>}</select></label><label class="font-semibold">Currency<input formControlName="currency" maxlength="3" placeholder="e.g. NGN" class="mt-1 min-h-11 w-full rounded-lg border px-3 uppercase"></label><label class="font-semibold">From date<input type="date" formControlName="from" class="mt-1 min-h-11 w-full rounded-lg border px-3"><span class="mt-1 block text-xs font-normal text-slate-500">Created on or after this date.</span></label><label class="font-semibold">To date<input type="date" formControlName="to" class="mt-1 min-h-11 w-full rounded-lg border px-3"><span class="mt-1 block text-xs font-normal text-slate-500">Created on or before this date.</span></label><div class="flex items-end gap-2"><button class="min-h-11 rounded-lg bg-brand-700 px-4 font-bold text-white">Apply</button><button type="button" (click)="reset()" class="min-h-11 rounded-lg border px-4 font-bold">Reset</button></div></form>
@if(historyLoading()){<p role="status" class="mt-4">Loading transactions…</p>}@else if(historyError()){<p role="alert" class="mt-4 rounded-xl bg-red-50 p-4">Transactions are unavailable. <button type="button" (click)="loadHistory(page())" class="font-bold underline">Try again</button></p>}@else if(!items().length){<p class="mt-4 rounded-xl border bg-white p-5">No earnings match these filters.</p>}@else{<div class="mt-4 overflow-x-auto rounded-xl border bg-white"><table class="min-w-[850px] w-full text-left"><thead><tr>@if(admin){<th class="p-3">Provider</th>}<th class="p-3">Source</th><th class="p-3">Reference</th><th class="p-3">Gross</th><th class="p-3">Commission</th><th class="p-3">{{admin?'Provider Share':'Your Share'}}</th><th class="p-3">Status</th><th class="p-3">Date</th><th class="p-3"></th></tr></thead><tbody>@for(e of items();track e.reference){<tr class="border-t">@if(admin){<td class="p-3">{{provider(e).displayName}}<span class="block text-xs">{{provider(e).reference}}</span></td>}<td class="p-3">{{source(e.sourceType)}}</td><td class="p-3 break-all">{{e.reference}}</td><td class="p-3">{{money(e.grossAmountMinor,e.currency)}}</td><td class="p-3">{{money(e.commissionAmountMinor,e.currency)}}</td><td class="p-3">{{money(e.providerShareMinor,e.currency)}}</td><td class="p-3"><span class="rounded-full bg-slate-100 px-2 py-1 font-semibold">{{status(e.status)}}</span></td><td class="p-3">{{date(e.createdAt)}}</td><td class="p-3"><a [routerLink]="[admin?'/admin/provider-earnings':'/provider/earnings',e.reference]" class="font-bold text-brand-700 underline">View</a></td></tr>}</tbody></table></div><div class="mt-4 flex justify-between"><button type="button" (click)="loadHistory(page()-1)" [disabled]="page()<=1">Previous</button><span>Page {{page()}} of {{totalPages()||1}}</span><button type="button" (click)="loadHistory(page()+1)" [disabled]="page()>=totalPages()">Next</button></div>}</section>}
</main>` })
export class EarningsPageComponent {
  private readonly api=inject(ProviderEarningsApiService);private readonly fb=inject(FormBuilder);readonly admin=inject(ActivatedRoute).snapshot.data['earningsScope']==='admin';
  readonly summaries=signal<readonly ProviderEarningCurrencySummary[]>([]);readonly items=signal<readonly ProviderEarning[]>([]);readonly initialLoading=signal(true);readonly summaryError=signal(false);readonly historyLoading=signal(false);readonly historyError=signal(false);readonly page=signal(1);readonly totalPages=signal(0);
  readonly statuses:ProviderEarningStatus[]=['HELD','PAYABLE','SETTLED','VOIDED'];readonly sources:ProviderEarningSourceType[]=['HEALTH_CHECK','GENERAL_CARE','PHARMACY_FULFILLMENT','PATIENT_REGISTRATION','PATIENT_LINKING'];readonly filters=this.fb.nonNullable.group({providerReference:'',status:'',sourceType:'',currency:'',from:'',to:''});readonly money=formatEarningMoney;readonly status=earningStatusLabel;readonly source=earningSourceLabel;
  constructor(){this.load()}load(){this.initialLoading.set(true);this.summaryError.set(false);const summary=this.admin?this.api.getAdminSummary():this.api.getProviderSummary();summary.pipe(finalize(()=>this.initialLoading.set(false))).subscribe({next:v=>this.summaries.set(v),error:()=>this.summaryError.set(true)});this.loadHistory(1)}
  apply(){this.loadHistory(1)}reset(){this.filters.reset();this.loadHistory(1)}loadHistory(page:number){if(page<1)return;this.historyLoading.set(true);this.historyError.set(false);const raw=this.filters.getRawValue();const filters={providerReference:raw.providerReference||undefined,status:(raw.status||undefined) as ProviderEarningStatus|undefined,sourceType:(raw.sourceType||undefined) as ProviderEarningSourceType|undefined,currency:raw.currency||undefined,from:raw.from?`${raw.from}T00:00:00.000Z`:undefined,to:raw.to?`${raw.to}T23:59:59.999Z`:undefined,page,limit:25};const request=this.admin?this.api.getAdminEarnings(filters):this.api.getProviderEarnings(filters);request.pipe(finalize(()=>this.historyLoading.set(false))).subscribe({next:value=>{this.items.set(value.items);this.page.set(value.page);this.totalPages.set(value.totalPages)},error:()=>this.historyError.set(true)})}
  provider(value:ProviderEarning){return (value as AdminProviderEarning).provider}date(value:string){return new Intl.DateTimeFormat('en-NG',{dateStyle:'medium'}).format(new Date(value))}
}
