import { TestBed } from '@angular/core/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { of } from 'rxjs';
import { ProviderPayoutDestination, ProviderPayoutDetail } from '../../core/models/provider-payout.model';
import { ProviderPayoutsApiService } from '../../core/services/provider-payouts-api.service';
import { PayoutDetailPageComponent } from './payout-detail-page.component';
const destination:ProviderPayoutDestination={payoutAccountReference:'SC-PACCT-ONE',type:'BANK_ACCOUNT',countryCode:'NG',currency:'NGN',bankCode:'058',bankName:'Old Bank Name',maskedAccountNumber:'****6789',accountName:'Prime Clinic'};
const detail=(status:ProviderPayoutDetail['status'],dest:ProviderPayoutDestination|null=null):ProviderPayoutDetail=>({reference:'SC-PAYOUT-ONE',currency:'NGN',totalAmountMinor:9000,earningCount:1,status,settlementMethod:'MANUAL_BANK_TRANSFER',destination:dest,externalReference:status==='COMPLETED'?'BANK-1':null,note:null,createdAt:'2026-08-30T09:00:00Z',processingAt:status==='DRAFT'?null:'2026-08-30T10:00:00Z',completedAt:status==='COMPLETED'?'2026-08-30T11:00:00Z':null,failedAt:null,cancelledAt:null,updatedAt:'2026-08-30T11:00:00Z',earnings:[{reference:'SC-EARN-1',sourceType:'GENERAL_CARE',sourceReference:'SC-CARE-1',providerShareMinor:9000,currency:'NGN',payableAt:'2026-08-30T08:00:00Z',settledAt:status==='COMPLETED'?'2026-08-30T11:00:00Z':null}],history:[{fromStatus:null,toStatus:'DRAFT',reasonCode:'PAYOUT_CREATED',reasonNote:null,createdAt:'2026-08-30T09:00:00Z'}]});
const route=(admin=false)=>({snapshot:{data:{payoutScope:admin?'admin':'provider'},paramMap:{get:()=> 'SC-PAYOUT-ONE'}}});
describe('PayoutDetailPageComponent destination snapshot',()=>{
 it('renders the immutable safe snapshot for the Provider without Admin controls',()=>{const api={getProviderPayout:()=>of(detail('COMPLETED',destination))};TestBed.configureTestingModule({imports:[PayoutDetailPageComponent],providers:[provideRouter([]),{provide:ActivatedRoute,useValue:route()},{provide:ProviderPayoutsApiService,useValue:api}]});const f=TestBed.createComponent(PayoutDetailPageComponent);f.detectChanges();const text=f.nativeElement.textContent;expect(text).toContain('Recorded payout destination');expect(text).toContain('Old Bank Name');expect(text).toContain('****6789');expect(text).not.toContain('Complete Settlement');expect(text).not.toContain('encryptedAccountNumber')});
 it('handles historical account-less payouts neutrally',()=>{const api={getProviderPayout:()=>of(detail('COMPLETED'))};TestBed.configureTestingModule({imports:[PayoutDetailPageComponent],providers:[provideRouter([]),{provide:ActivatedRoute,useValue:route()},{provide:ProviderPayoutsApiService,useValue:api}]});const f=TestBed.createComponent(PayoutDetailPageComponent);f.detectChanges();expect(f.nativeElement.textContent).toContain('Recorded payout destination');expect(f.nativeElement.textContent).toContain('Not recorded')});
 it('makes a PROCESSING Admin destination prominent while preserving lifecycle actions',()=>{const api={getAdminPayout:()=>of({...detail('PROCESSING',destination),provider:{reference:'SCPR-ONE',displayName:'Prime'}})};TestBed.configureTestingModule({imports:[PayoutDetailPageComponent],providers:[provideRouter([]),{provide:ActivatedRoute,useValue:route(true)},{provide:ProviderPayoutsApiService,useValue:api}]});const f=TestBed.createComponent(PayoutDetailPageComponent);f.detectChanges();const text=f.nativeElement.textContent;expect(text).toContain('****6789');expect(text).toContain('Only the masked account number');expect(text).toContain('Complete Settlement');expect(text).toContain('Mark Failed')});
});
