import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { ShareableHealthPassport, ShareablePassportHealthCheck, ShareablePassportMeasurement } from '../../core/models/clinical-record.model';
import { ClinicalRecordsApiService } from '../../core/services/clinical-records-api.service';

@Component({
  selector: 'app-provider-shared-health-passport-page', imports: [RouterLink], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<main class="mx-auto max-w-6xl px-5 py-10 sm:px-8"><a routerLink="/provider/health-record-access" class="font-bold text-brand-700 underline">← Health Record Access</a>
  @if(loading()){<p role="status" class="mt-8 rounded-2xl border bg-white p-6">Loading Health Passport…</p>}
  @else if(error()){<section role="alert" class="mt-8 rounded-2xl bg-red-50 p-6"><h1 class="text-xl font-bold">Health Passport unavailable</h1><p class="mt-2">We couldn't open this shared Health Passport. The permission may be unavailable or no longer active.</p><button type="button" (click)="load()" class="mt-3 font-bold underline">Try again</button></section>}
  @else if(passport();as p){<header class="mt-6 rounded-2xl border bg-white p-6"><p class="text-sm font-bold uppercase text-brand-600">{{p.authorization.includesFinalizedClinicalRecords?'Health Passport + finalized records':'Shared Health Passport access'}}</p><h1 class="mt-2 text-3xl font-bold">Health Passport</h1><dl class="mt-5 grid gap-4 sm:grid-cols-3"><div><dt class="text-sm text-slate-500">Patient</dt><dd class="font-bold">{{p.patient.displayName}}</dd></div><div><dt class="text-sm text-slate-500">Patient reference</dt><dd class="break-all font-bold">{{p.patient.patientReference}}</dd></div><div><dt class="text-sm text-slate-500">Date of birth</dt><dd>{{p.patient.dateOfBirth||'Not available'}}</dd></div></dl></header>
  <div class="mt-6 grid gap-6 lg:grid-cols-2"><section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">Guided Self-Checks</h2>@if(!p.guidedSelfChecks.length){<p class="mt-3 text-slate-600">No completed Guided Self-Checks shared.</p>}@else{<div class="mt-4 grid gap-4">@for(check of p.guidedSelfChecks;track check.eventKey){<article class="rounded-xl bg-slate-50 p-4"><div class="flex flex-wrap justify-between gap-2"><strong>{{check.title}}</strong><time>{{date(check.occurredAt)}}</time></div><p class="mt-2">{{check.description}}</p>@if(check.context.classification){<p class="mt-2"><span class="font-bold">Classification:</span> {{label(check.context.classification)}}</p>}<p class="mt-2 text-sm">{{provenance(check.provenance)}} · {{check.sourceReference}}</p></article>}</div>}</section>
  <section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">Reported health history</h2>@if(!p.reportedHealthHistory.length){<p class="mt-3 text-slate-600">No patient-reported history shared.</p>}@else{<dl class="mt-4 grid gap-4">@for(item of p.reportedHealthHistory;track item.key){<div class="rounded-xl bg-slate-50 p-4"><dt class="font-bold">{{item.label}}</dt><dd class="mt-1">{{displayValue(item.value)}}</dd><dd class="mt-2 text-sm text-slate-600">{{provenance(item.provenance)}} · {{date(item.reportedAt)}}</dd></div>}</dl>}</section>
  <section class="rounded-2xl border bg-white p-6 lg:col-span-2"><h2 class="text-xl font-bold">Reported measurements</h2>@if(!p.reportedMeasurements.length){<p class="mt-3 text-slate-600">No patient-reported measurements shared.</p>}@else{<div class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@for(item of p.reportedMeasurements;track item.type+item.sourceReference+item.recordedAt){<article class="rounded-xl bg-slate-50 p-4"><h3 class="font-bold">{{label(item.type)}}</h3><p class="mt-2 text-xl font-bold">{{measurement(item)}}</p><p class="mt-2 text-sm text-slate-600">{{provenance(item.provenance)}} · {{date(item.recordedAt)}}</p></article>}</div>}</section>
  <section class="rounded-2xl border bg-white p-6 lg:col-span-2"><h2 class="text-xl font-bold">Completed Health Checks</h2>@if(!p.healthChecks.length){<p class="mt-3 text-slate-600">No completed Health Checks shared.</p>}@else{<div class="mt-4 grid gap-5">@for(check of p.healthChecks;track check.reference){<article class="rounded-xl border p-5"><div class="flex flex-wrap justify-between gap-3"><div><h3 class="text-lg font-bold">{{check.package.name}}</h3><p>{{check.provider.displayName}} · {{check.fulfilmentMode.name}}</p></div><time>{{date(check.completedAt)}}</time></div><p class="mt-2 break-all text-xs text-slate-500">{{check.reference}}</p><div class="mt-4 grid gap-3 sm:grid-cols-2">@for(work of check.clinicalWork;track work.code){<div class="rounded-xl bg-slate-50 p-4"><strong>{{work.name}}</strong>@if(result(check,work.code);as value){<p class="mt-2 text-lg font-bold">{{resultValue(value)}}</p>}@else if(work.resultType==='NONE'){<p class="mt-2 text-sm text-slate-600">Clinical work item; no numeric result.</p>}@else{<p class="mt-2 text-sm text-slate-600">No result included.</p>}</div>}</div></article>}</div>}</section>
  <section class="rounded-2xl border bg-white p-6 lg:col-span-2"><h2 class="text-xl font-bold">Finalized clinical records</h2>@if(!p.authorization.includesFinalizedClinicalRecords){<p class="mt-3 text-slate-600">This sharing permission covers the Health Passport only; standalone clinical records are not included.</p>}@else if(!p.clinicalRecords.length){<p class="mt-3 text-slate-600">No finalized clinical records were returned.</p>}@else{<div class="mt-4 grid gap-4 sm:grid-cols-2">@for(record of p.clinicalRecords;track record.reference){<article class="rounded-xl border p-4"><h3 class="font-bold">{{record.title}}</h3><p class="mt-1">{{label(record.recordType)}} · {{record.provider.displayName}}</p>@if(record.summary){<p class="mt-2 text-slate-600">{{record.summary}}</p>}<p class="mt-2 text-sm">{{date(record.occurredAt)}}</p></article>}</div>}</section></div>}
  </main>`,
})
export class ProviderSharedHealthPassportPageComponent {
  private readonly api=inject(ClinicalRecordsApiService); readonly patientReference=inject(ActivatedRoute).snapshot.paramMap.get('patientReference')??''; readonly passport=signal<ShareableHealthPassport|null>(null); readonly loading=signal(true); readonly error=signal(false);
  constructor(){this.load();} load(){this.loading.set(true);this.error.set(false);this.api.getSharedHealthPassport(this.patientReference).pipe(finalize(()=>this.loading.set(false))).subscribe({next:value=>this.passport.set(value),error:()=>this.error.set(true)});}
  result(check:ShareablePassportHealthCheck,code:string){return check.results.find(item=>item.code===code);} resultValue(value:ShareablePassportHealthCheck['results'][number]){return value.resultType==='BLOOD_PRESSURE'?`${this.displayValue(value.value.systolic)}/${this.displayValue(value.value.diastolic)}${value.unit?' '+value.unit:''}`:`${this.displayValue(value.value.value)}${value.unit?' '+value.unit:''}`;}
  measurement(item:ShareablePassportMeasurement){const v=item.value;const raw=v.systolic!==undefined||v.primary!==undefined?`${this.displayValue(v.systolic??v.primary)}/${this.displayValue(v.diastolic??v.secondary)}`:this.displayValue(v.value);return `${raw}${item.unit?' '+item.unit:''}`;}
  displayValue(value:unknown):string{if(Array.isArray(value))return value.map(item=>this.displayValue(item)).join(', ');if(value&&typeof value==='object')return Object.values(value as Record<string,unknown>).map(item=>this.displayValue(item)).join(', ');return value===null||value===undefined||value===''?'Not reported':String(value);} provenance(value:string){return value==='REPORTED_BY_YOU'?'Patient reported':'Checked by provider';} label(value:string){return value.split('_').map(x=>x[0]+x.slice(1).toLowerCase()).join(' ');} date(value:string){return new Intl.DateTimeFormat('en-NG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
}
