import { ChangeDetectionStrategy,Component,inject,signal } from '@angular/core';import { FormBuilder,ReactiveFormsModule,Validators } from '@angular/forms';import { finalize } from 'rxjs';import { GrowthInvite,ProviderNetworkApiService } from '../../core/services/provider-network-api.service';
@Component({selector:'app-provider-network-page',imports:[ReactiveFormsModule],changeDetection:ChangeDetectionStrategy.OnPush,template:`
<main class="mx-auto max-w-6xl px-5 py-10 sm:px-8"><header class="overflow-hidden rounded-[2rem] border bg-white p-7 shadow-sm"><p class="text-xs font-bold uppercase tracking-[.2em] text-brand-700">Grow with SmartClinic</p><h1 class="mt-2 text-3xl font-black text-slate-950">Grow your healthcare network</h1><p class="mt-3 max-w-3xl text-slate-600">Invite a pharmacy, laboratory or clinic you trust. They complete their own verification. When an invited provider becomes active, eligible business they complete can contribute to your network earnings.</p><div class="mt-5 rounded-2xl bg-brand-50 p-4"><strong>Impact that keeps growing.</strong><p class="mt-1 text-sm text-slate-700">The more useful healthcare connections you create, the more patients get access—and your eligible network earnings can grow with that impact.</p></div></header>
<div class="mt-7 grid gap-6 lg:grid-cols-[1fr_1.1fr]"><section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">Recommend a provider</h2><p class="mt-1 text-sm text-slate-600">You only need enough information for SmartClinic to invite them. The provider finishes the rest.</p>
<form [formGroup]="form" (ngSubmit)="submit()" class="mt-5 grid gap-4">
<label class="font-semibold">Provider type<select formControlName="targetType" class="mt-1 w-full rounded-xl border p-3"><option value="PHARMACY">Pharmacy</option><option value="LABORATORY">Laboratory / diagnostic centre</option><option value="CLINIC">Clinic</option></select></label>
<label class="font-semibold">Business name<input formControlName="businessName" class="mt-1 w-full rounded-xl border p-3" placeholder="e.g. Unity Pharmacy"></label>
<label class="font-semibold">Contact person <span class="font-normal text-slate-500">(optional)</span><input formControlName="contactName" class="mt-1 w-full rounded-xl border p-3"></label>
<div class="grid gap-3 sm:grid-cols-2"><label class="font-semibold">Email<input type="email" formControlName="email" class="mt-1 w-full rounded-xl border p-3"></label><label class="font-semibold">Phone<input formControlName="phone" class="mt-1 w-full rounded-xl border p-3"></label></div><p class="-mt-2 text-xs text-slate-500">Add at least an email or phone number.</p>
<div class="grid gap-3 sm:grid-cols-3"><label class="font-semibold">Country<input formControlName="countryCode" maxlength="2" class="mt-1 w-full rounded-xl border p-3"></label><label class="font-semibold">State / region<input formControlName="stateOrRegion" class="mt-1 w-full rounded-xl border p-3"></label><label class="font-semibold">City<input formControlName="city" class="mt-1 w-full rounded-xl border p-3"></label></div>
<label class="font-semibold">Address <span class="font-normal text-slate-500">(optional)</span><input formControlName="address" class="mt-1 w-full rounded-xl border p-3"></label>
@if(error()){<p role="alert" class="rounded-xl bg-red-50 p-3 text-red-800">{{error()}}</p>}@if(success()){<div class="rounded-xl bg-green-50 p-4 text-green-900"><strong>Invitation ready.</strong><p class="mt-1 text-sm">Share the secure link with the provider so they can complete their profile.</p><button type="button" (click)="shareLast()" class="mt-3 rounded-lg bg-brand-700 px-4 py-2 font-bold text-white">Share invitation</button></div>}
<button [disabled]="form.invalid||saving()" class="min-h-12 rounded-xl bg-brand-700 px-5 font-bold text-white disabled:opacity-50">{{saving()?'Creating invitation…':'Create invitation'}}</button></form></section>
<section class="rounded-2xl border bg-white p-6"><div class="flex items-center justify-between"><div><h2 class="text-xl font-bold">Your network</h2><p class="mt-1 text-sm text-slate-600">Follow each provider from invitation to activation.</p></div><button type="button" (click)="load()" class="font-bold text-brand-700">Refresh</button></div>
@if(loading()){<p class="mt-5 rounded-xl bg-slate-50 p-4">Loading your network…</p>}@else if(invites().length){<div class="mt-5 grid gap-3">@for(item of invites();track item.reference){<article class="rounded-2xl border p-4"><div class="flex items-start justify-between gap-3"><div><p class="font-bold text-slate-950">{{item.businessName}}</p><p class="text-sm text-slate-600">{{label(item.targetType)}} · {{item.city}}, {{item.stateOrRegion}}</p></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{{status(item.status)}}</span></div><div class="mt-3 flex justify-between text-sm"><span>Network share</span><strong>{{item.referrerSharePercent}}%</strong></div></article>}</div>}@else{<div class="mt-5 rounded-2xl bg-slate-50 p-6"><p class="font-bold">Your network starts with one useful connection.</p><p class="mt-1 text-sm text-slate-600">Recommend a provider you already know instead of waiting for SmartClinic to find them.</p></div>}</section></div>
<p class="mt-6 text-sm text-slate-500">Network earnings apply only to eligible completed business under SmartClinic's active commercial rules. Provider verification and patient choice remain independent of referral rewards.</p></main>`})
export class ProviderNetworkPageComponent{private api=inject(ProviderNetworkApiService);private fb=inject(FormBuilder);invites=signal<GrowthInvite[]>([]);loading=signal(true);saving=signal(false);error=signal<string|null>(null);success=signal<GrowthInvite|null>(null);form=this.fb.nonNullable.group({targetType:['PHARMACY' as const,Validators.required],businessName:['',Validators.required],contactName:[''],email:[''],phone:[''],countryCode:['NG',[Validators.required,Validators.minLength(2)]],stateOrRegion:['',Validators.required],city:['',Validators.required],address:['']});constructor(){this.load()}load(){this.loading.set(true);this.api.list().pipe(finalize(()=>this.loading.set(false))).subscribe({next:v=>this.invites.set(v),error:()=>this.invites.set([])})}submit(){if(this.form.invalid||(!this.form.value.email&&!this.form.value.phone)){this.error.set('Add an email or phone number for the provider.');return}this.saving.set(true);this.error.set(null);this.api.create(this.form.getRawValue()).pipe(finalize(()=>this.saving.set(false))).subscribe({next:v=>{this.success.set(v);this.load()},error:()=>this.error.set('We could not create this invitation. Check the details and try again.')})}async shareLast(){const v=this.success();if(!v?.claimUrl)return;const url=new URL(v.claimUrl,window.location.origin).toString();if(navigator.share)await navigator.share({title:'Join SmartClinic',text:`You've been recommended to join SmartClinic as ${v.businessName}. Complete your provider profile here.`,url});else await navigator.clipboard.writeText(url)}label(v:string){return v==='LABORATORY'?'Laboratory / diagnostic centre':v[0]+v.slice(1).toLowerCase()}status(v:string){return ({INVITED:'Invitation sent',CLAIMED:'Profile started',ACTIVATED:'Active',EXPIRED:'Expired',CANCELLED:'Cancelled'} as Record<string,string>)[v]??v}}
