import { TestBed } from '@angular/core/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { of, throwError } from 'rxjs';
import { ClinicalRecordsApiService } from '../../core/services/clinical-records-api.service';
import { ProviderCareOperationsApiService } from '../../core/services/provider-care-operations-api.service';
import { ProviderCareServicesApiService } from '../../core/services/provider-care-services-api.service';
import { ProviderCareAppointmentDetailPageComponent } from './provider-care-appointment-detail-page.component';

describe('ProviderCareAppointmentDetailPageComponent clinical records', () => {
  async function setup(record: ReturnType<typeof clinicalRecord> | null = clinicalRecord(), type: string | null = 'CONSULTATION', status: 'SCHEDULED' | 'CONFIRMED' | 'IN_PROGRESS' = 'IN_PROGRESS') {
    let current = appointment(status);
    const operations = { getAppointment: vi.fn(() => of(current)), completeAppointment: vi.fn(() => of(current)), startAppointment: vi.fn(() => { current = appointment('IN_PROGRESS'); return of(current); }), markNoShow: vi.fn(), cancelAppointment: vi.fn(), updateMeetingLink: vi.fn() };
    const careServices = { getCatalogue: vi.fn(() => of([{ id: 'definition', code: 'GENERAL_CONSULTATION', name: 'General Consultation', description: null, isActive: true, clinicalRecordType: type }])) };
    const records = { getForProviderAppointment: vi.fn((_reference: string) => record ? of(record) : throwError(() => ({ status: 404 }))), createForProviderAppointment: vi.fn((_reference: string, _body: unknown) => of(clinicalRecord())), updateForProviderAppointment: vi.fn((_reference: string, _body: unknown) => of(clinicalRecord())), finalizeForProviderAppointment: vi.fn((_reference: string) => of({ ...clinicalRecord(), status: 'FINALIZED' })) };
    await TestBed.configureTestingModule({ imports: [ProviderCareAppointmentDetailPageComponent], providers: [provideRouter([]), { provide: ActivatedRoute, useValue: { snapshot: { paramMap: { get: () => 'SC-APT-1' } } } }, { provide: ProviderCareOperationsApiService, useValue: operations }, { provide: ProviderCareServicesApiService, useValue: careServices }, { provide: ClinicalRecordsApiService, useValue: records }] }).compileComponents();
    const fixture = TestBed.createComponent(ProviderCareAppointmentDetailPageComponent); fixture.detectChanges();
    return { fixture, operations, records };
  }
  it.each(['SCHEDULED', 'CONFIRMED'] as const)('%s shows pre-start guidance without a manual create action', async status => { const { fixture, records } = await setup(null, 'CONSULTATION', status); expect(fixture.nativeElement.textContent).toContain('Clinical documentation will be available when the appointment starts'); expect(fixture.nativeElement.textContent).not.toContain('Create consultation record'); expect(records.getForProviderAppointment).not.toHaveBeenCalled(); });
  it('reloads appointment and the backend-created record after Start without posting a record', async () => { const { fixture, operations, records } = await setup(clinicalRecord(), 'CONSULTATION', 'SCHEDULED'); const c = fixture.componentInstance; c.start(); fixture.detectChanges(); expect(operations.startAppointment).toHaveBeenCalledWith('SC-APT-1'); expect(operations.getAppointment).toHaveBeenCalledTimes(2); expect(records.getForProviderAppointment).toHaveBeenCalledWith('SC-APT-1'); expect(records.createForProviderAppointment).not.toHaveBeenCalled(); expect(fixture.nativeElement.textContent).toContain('Draft'); });
  it('shows an in-progress missing-record inconsistency with retry and no create fallback', async () => { const { fixture, records } = await setup(null); expect(fixture.nativeElement.textContent).toContain('Clinical record could not be loaded. Refresh and try again.'); expect(fixture.nativeElement.textContent).not.toContain('Create consultation record'); expect(fixture.nativeElement.textContent).toContain('Try again'); expect(records.createForProviderAppointment).not.toHaveBeenCalled(); });
  it('populates and updates a draft, then requires finalization', async () => { const { fixture, records } = await setup(clinicalRecord()); const c = fixture.componentInstance; c.openRecordForm(); expect(c.recordForm.controls.diagnosis.value).toBe('Assessment'); c.recordForm.controls.diagnosis.setValue('Updated'); c.saveClinicalRecord(); expect(records.updateForProviderAppointment).toHaveBeenCalled(); expect(c.completionBlockMessage()).toContain('Finalize'); });
  it('finalizes only after confirmation and makes a finalized record read-only', async () => { const { fixture, records } = await setup(clinicalRecord()); const c = fixture.componentInstance; c.finalizeOpen.set(true); fixture.detectChanges(); expect(fixture.nativeElement.querySelector('[role="alertdialog"]')).not.toBeNull(); c.finalizeClinicalRecord(); expect(records.finalizeForProviderAppointment).toHaveBeenCalledWith('SC-APT-1'); c.clinicalRecord.set({ ...clinicalRecord(), status: 'FINALIZED', finalizedAt: '2026-08-29T09:00:00Z' }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).not.toContain('Edit clinical record'); expect(c.completionBlockMessage()).toBeNull(); });
  it('shows a safe placeholder for unsupported structured types', async () => { const { fixture } = await setup(clinicalRecord('LAB_RESULT'), 'LAB_RESULT'); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Structured entry for this record type is not available yet'); });
  it('leaves completion ungated when the service has no record requirement', async () => { const { fixture, records } = await setup(null, null); expect(fixture.componentInstance.completionBlockMessage()).toBeNull(); expect(records.getForProviderAppointment).not.toHaveBeenCalled(); });
});
function appointment(status: 'SCHEDULED' | 'CONFIRMED' | 'IN_PROGRESS' = 'IN_PROGRESS') { return { appointmentReference: 'SC-APT-1', careRequestReference: 'SC-CARE-1', status, deliveryMode: 'IN_PERSON' as const, service: { code: 'GENERAL_CONSULTATION', name: 'General Consultation' }, provider: { providerReference: 'SCPR-1', displayName: 'Clinic', providerType: 'CLINIC' }, providerLocation: null, scheduledDate: '2026-08-29', scheduledTimeFrom: '10:00', scheduledTimeTo: '10:30', timezone: 'Africa/Lagos', notes: null, meetingUrl: null, createdAt: '2026-08-29T08:00:00Z', updatedAt: '2026-08-29T08:00:00Z' }; }
function clinicalRecord(recordType: 'CONSULTATION' | 'LAB_RESULT' = 'CONSULTATION') { return { reference: 'SC-CLR-1', recordType, title: 'Consultation outcome', summary: null, status: 'DRAFT' as const, occurredAt: '2026-08-29T10:00:00Z', finalizedAt: null, provider: { providerReference: 'SCPR-1', displayName: 'Clinic', providerType: 'CLINIC' }, careRequestReference: 'SC-CARE-1', careAppointmentReference: 'SC-APT-1', service: { code: 'GENERAL_CONSULTATION', name: 'General Consultation' }, consultation: recordType === 'CONSULTATION' ? { presentingComplaint: null, historyOfPresentingComplaint: null, observations: null, assessment: null, diagnosis: 'Assessment', plan: null, followUpInstructions: null } : null, createdAt: '2026-08-29T10:00:00Z', updatedAt: '2026-08-29T10:00:00Z' }; }
