import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { ClinicalRecordAccessRequest, ClinicalRecordAccessScope, ClinicalRecordType, CreateClinicalRecordAccessRequest } from '../../core/models/clinical-record.model';
import { ClinicalRecordsApiService } from '../../core/services/clinical-records-api.service';

@Component({
  selector: 'app-provider-health-record-access-page', imports: [ReactiveFormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<main class="mx-auto max-w-6xl px-5 py-10 sm:px-8"><p class="text-sm font-bold uppercase text-brand-600">Provider portal</p><div class="mt-2 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-3xl font-bold">Health Record Access</h1><p class="mt-2 text-slate-600">Request patient consent. Sending a request does not provide record access.</p></div><button type="button" (click)="showForm.set(!showForm())" class="rounded-xl bg-brand-700 px-5 py-3 font-bold text-white">Request access</button></div>
  @if(showForm()){<form [formGroup]="form" (ngSubmit)="submit()" class="mt-8 grid gap-5 rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">Request access</h2><label class="grid gap-2 font-bold">Patient reference<input formControlName="patientReference" placeholder="SCP-AB12-CD34" class="rounded-xl border p-3" /></label><fieldset class="grid gap-3"><legend class="font-bold">Scope</legend><label><input type="radio" formControlName="scope" value="ALL_RECORDS"> All finalized records</label><label><input type="radio" formControlName="scope" value="RECORD_TYPE"> One record type</label><label><input type="radio" formControlName="scope" value="SINGLE_RECORD"> One record</label></fieldset>
  @if(form.controls.scope.value==='RECORD_TYPE'){<label class="grid gap-2 font-bold">Record type<select formControlName="recordType" class="rounded-xl border p-3"><option value="">Select type</option>@for(type of recordTypes;track type){<option [value]="type">{{label(type)}}</option>}</select></label>}
  @if(form.controls.scope.value==='SINGLE_RECORD'){<label class="grid gap-2 font-bold">Clinical record reference<input formControlName="clinicalRecordReference" class="rounded-xl border p-3" /></label>}
  <label class="grid gap-2 font-bold">Reason for access<textarea formControlName="reason" maxlength="1000" placeholder="e.g. Coordinate ongoing care" class="min-h-28 rounded-xl border p-3"></textarea></label><label class="grid gap-2 font-bold">Requested expiry <span class="text-sm font-normal text-slate-600">Optional; this is the requested expiry for the eventual sharing permission.</span><input type="datetime-local" formControlName="requestedExpiresAt" class="rounded-xl border p-3" /></label>
  @if(error()){<p role="alert" class="rounded-xl bg-red-50 p-4">{{error()}}</p>}@if(success()){<p role="status" class="rounded-xl bg-green-50 p-4">Access request sent. The patient must approve the request before you can view their health records.</p>}<button type="submit" [disabled]="saving()" class="rounded-xl bg-brand-700 px-5 py-3 font-bold text-white">{{saving()?'Sending…':'Send access request'}}</button></form>}
  @if(loading()){<p role="status" class="mt-8 rounded-2xl border p-6">Loading requests…</p>}@else if(listError()){<p role="alert" class="mt-8 rounded-2xl bg-red-50 p-6">Unable to load access requests. <button type="button" (click)="load()" class="font-bold underline">Try again</button></p>}@else{<section class="mt-8"><h2 class="text-xl font-bold">Requests sent</h2>@if(!items().length){<p class="mt-4 rounded-2xl border bg-white p-6">No access requests sent yet.</p>}@else{<div class="mt-4 grid gap-4">@for(request of items();track request.reference){<article class="rounded-2xl border bg-white p-5"><div class="flex flex-wrap justify-between gap-3"><strong>{{request.patient.patientReference}}</strong><span class="font-bold">{{label(request.status)}}</span></div><dl class="mt-4 grid gap-3 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Scope</dt><dd>{{scope(request)}}</dd></div><div><dt class="text-sm text-slate-500">Reason</dt><dd>{{request.reason}}</dd></div><div><dt class="text-sm text-slate-500">Requested until</dt><dd>{{request.requestedExpiresAt?date(request.requestedExpiresAt):'No requested expiry'}}</dd></div><div><dt class="text-sm text-slate-500">Requested</dt><dd>{{date(request.createdAt)}}</dd></div></dl>@if(request.status==='APPROVED'){<a routerLink="/provider/shared-health-records" class="mt-4 inline-block font-bold text-brand-700 underline">View shared records</a>}</article>}</div>}</section>}</main>`,
})
export class ProviderHealthRecordAccessPageComponent {
  private readonly api=inject(ClinicalRecordsApiService); readonly showForm=signal(false); readonly saving=signal(false); readonly success=signal(false); readonly error=signal(''); readonly loading=signal(true); readonly listError=signal(false); readonly items=signal<readonly ClinicalRecordAccessRequest[]>([]); readonly recordTypes:readonly ClinicalRecordType[]=['CONSULTATION','LAB_RESULT','IMAGING_RESULT','PROCEDURE','PHARMACY','FOLLOW_UP','OTHER'];
  readonly form=new FormGroup({patientReference:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.pattern(/^SCP-[A-Z0-9]{4}-[A-Z0-9]{4}$/)]}),scope:new FormControl<ClinicalRecordAccessScope>('ALL_RECORDS',{nonNullable:true}),recordType:new FormControl<ClinicalRecordType|''>('',{nonNullable:true}),clinicalRecordReference:new FormControl('',{nonNullable:true}),reason:new FormControl('',{nonNullable:true,validators:[Validators.required,Validators.maxLength(1000)]}),requestedExpiresAt:new FormControl('',{nonNullable:true})});
  constructor(){this.load();}
  load(){this.loading.set(true);this.listError.set(false);this.api.listProviderAccessRequests(1,100).pipe(finalize(()=>this.loading.set(false))).subscribe({next:p=>this.items.set(p.items),error:()=>this.listError.set(true)});}
  submit(){this.error.set('');this.success.set(false);const v=this.form.getRawValue(),scope=v.scope;if(this.form.invalid||(scope==='RECORD_TYPE'&&!v.recordType)||(scope==='SINGLE_RECORD'&&!v.clinicalRecordReference.trim())){this.form.markAllAsTouched();this.error.set('Complete the patient, scope and reason details.');return;}const body:CreateClinicalRecordAccessRequest={patientReference:v.patientReference.trim().toUpperCase(),scope,reason:v.reason.trim(),...(scope==='RECORD_TYPE'?{recordType:v.recordType as ClinicalRecordType}:{}),...(scope==='SINGLE_RECORD'?{clinicalRecordReference:v.clinicalRecordReference.trim()}:{}),...(v.requestedExpiresAt?{requestedExpiresAt:new Date(v.requestedExpiresAt).toISOString()}: {})};this.saving.set(true);this.api.createProviderAccessRequest(body).pipe(finalize(()=>this.saving.set(false))).subscribe({next:r=>{this.items.update(items=>[r,...items]);this.success.set(true);this.form.reset({patientReference:'',scope:'ALL_RECORDS',recordType:'',clinicalRecordReference:'',reason:'',requestedExpiresAt:''});},error:()=>this.error.set('The access request could not be sent. Review the details and try again.')});}
  scope(r:ClinicalRecordAccessRequest){return r.scope==='ALL_RECORDS'?'All finalized records':r.scope==='RECORD_TYPE'?`${this.label(r.recordType??'')} records`:`Single record (${r.clinicalRecordReference})`;}
  label(value:string){return value.split('_').map(x=>x[0]+x.slice(1).toLowerCase()).join(' ');} date(value:string){return new Intl.DateTimeFormat('en-NG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
}
