import { TestBed } from '@angular/core/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { of, throwError } from 'rxjs';
import { ClinicalRecordsApiService } from '../../core/services/clinical-records-api.service';
import { ProviderCareOperationsApiService } from '../../core/services/provider-care-operations-api.service';
import { ProviderCareServicesApiService } from '../../core/services/provider-care-services-api.service';
import { ProviderCareAppointmentDetailPageComponent } from './provider-care-appointment-detail-page.component';
import { ClinicalRecord } from '../../core/models/clinical-record.model';
import { PharmacyFulfillmentApiService } from '../../core/services/pharmacy-fulfillment-api.service';

describe('ProviderCareAppointmentDetailPageComponent clinical records', () => {
  async function setup(record: ReturnType<typeof clinicalRecord> | null = clinicalRecord(), type: string | null = 'CONSULTATION', status: 'SCHEDULED' | 'CONFIRMED' | 'IN_PROGRESS' = 'IN_PROGRESS') {
    let current = appointment(status);
    const operations = { getAppointment: vi.fn(() => of(current)), completeAppointment: vi.fn(() => of(current)), startAppointment: vi.fn(() => { current = appointment('IN_PROGRESS'); return of(current); }), markNoShow: vi.fn(), cancelAppointment: vi.fn(), updateMeetingLink: vi.fn() };
    const careServices = { getCatalogue: vi.fn(() => of([{ id: 'definition', code: 'GENERAL_CONSULTATION', name: 'General Consultation', description: null, isActive: true, clinicalRecordType: type }])) };
    const records = { getForProviderAppointment: vi.fn((_reference: string) => record ? of(record) : throwError(() => ({ status: 404 }))), createForProviderAppointment: vi.fn((_reference: string, _body: unknown) => of(clinicalRecord())), updateForProviderAppointment: vi.fn((_reference: string, _body: unknown) => of(clinicalRecord())), finalizeForProviderAppointment: vi.fn((_reference: string) => of({ ...clinicalRecord(), status: 'FINALIZED' })), uploadAttachment: vi.fn((_reference: string, _file: File) => of(attachment())), deleteAttachment: vi.fn(() => of({ deleted: true })), getProviderAttachmentAccess: vi.fn(() => of({ url: 'https://files.example.test/file', expiresAt: '2026-08-29T11:00:00Z' })) };
    const pharmacy = { listAppointmentOrders: vi.fn(() => of({ items: [], page: 1, limit: 20, total: 0, totalPages: 0 })) };
    await TestBed.configureTestingModule({ imports: [ProviderCareAppointmentDetailPageComponent], providers: [provideRouter([]), { provide: ActivatedRoute, useValue: { snapshot: { paramMap: { get: () => 'SC-APT-1' } } } }, { provide: ProviderCareOperationsApiService, useValue: operations }, { provide: ProviderCareServicesApiService, useValue: careServices }, { provide: ClinicalRecordsApiService, useValue: records }, { provide: PharmacyFulfillmentApiService, useValue: pharmacy }] }).compileComponents();
    const fixture = TestBed.createComponent(ProviderCareAppointmentDetailPageComponent); fixture.detectChanges();
    return { fixture, operations, records };
  }
  it.each(['SCHEDULED', 'CONFIRMED'] as const)('%s shows pre-start guidance without a manual create action', async status => { const { fixture, records } = await setup(null, 'CONSULTATION', status); expect(fixture.nativeElement.textContent).toContain('Clinical documentation will be available when the appointment starts'); expect(fixture.nativeElement.textContent).not.toContain('Create consultation record'); expect(records.getForProviderAppointment).not.toHaveBeenCalled(); });
  it('reloads appointment and the backend-created record after Start without posting a record', async () => { const { fixture, operations, records } = await setup(clinicalRecord(), 'CONSULTATION', 'SCHEDULED'); const c = fixture.componentInstance; c.start(); fixture.detectChanges(); expect(operations.startAppointment).toHaveBeenCalledWith('SC-APT-1'); expect(operations.getAppointment).toHaveBeenCalledTimes(2); expect(records.getForProviderAppointment).toHaveBeenCalledWith('SC-APT-1'); expect(records.createForProviderAppointment).not.toHaveBeenCalled(); expect(fixture.nativeElement.textContent).toContain('Draft'); });
  it('shows an in-progress missing-record inconsistency with retry and no create fallback', async () => { const { fixture, records } = await setup(null); expect(fixture.nativeElement.textContent).toContain('Clinical record could not be loaded. Refresh and try again.'); expect(fixture.nativeElement.textContent).not.toContain('Create consultation record'); expect(fixture.nativeElement.textContent).toContain('Try again'); expect(records.createForProviderAppointment).not.toHaveBeenCalled(); });
  it('populates and updates a draft, then requires finalization', async () => { const { fixture, records } = await setup(clinicalRecord()); const c = fixture.componentInstance; c.openRecordForm(); expect(c.recordForm.controls.diagnosis.value).toBe('Assessment'); c.recordForm.controls.diagnosis.setValue('Updated'); c.saveClinicalRecord(); expect(records.updateForProviderAppointment).toHaveBeenCalled(); expect(c.completionBlockMessage()).toContain('Finalize'); });
  it('finalizes only after confirmation and makes a finalized record read-only', async () => { const { fixture, records } = await setup(clinicalRecord()); const c = fixture.componentInstance; c.finalizeOpen.set(true); fixture.detectChanges(); expect(fixture.nativeElement.querySelector('[role="alertdialog"]')).not.toBeNull(); c.finalizeClinicalRecord(); expect(records.finalizeForProviderAppointment).toHaveBeenCalledWith('SC-APT-1'); c.clinicalRecord.set({ ...clinicalRecord(), status: 'FINALIZED', finalizedAt: '2026-08-29T09:00:00Z' }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).not.toContain('Edit clinical record'); expect(c.completionBlockMessage()).toBeNull(); });
  it('renders and saves a template-driven record from its immutable snapshot', async () => { const { fixture, records } = await setup(clinicalRecord('LAB_RESULT'), 'LAB_RESULT'); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Result summary'); fixture.componentInstance.saveStructuredRecord({ resultSummary: 'Normal' }); expect(records.updateForProviderAppointment).toHaveBeenCalledWith('SC-APT-1', { structuredData: { resultSummary: 'Normal' } }); });
  it('leaves completion ungated when the service has no record requirement', async () => { const { fixture, records } = await setup(null, null); expect(fixture.componentInstance.completionBlockMessage()).toBeNull(); expect(records.getForProviderAppointment).not.toHaveBeenCalled(); });
  it('shows upload only for a draft and validates MIME, size, and the five-file limit', async () => {
    const { fixture } = await setup(); const c = fixture.componentInstance; expect(fixture.nativeElement.textContent).toContain('Attach supporting clinical documents or images');
    c.selectAttachment(fileEvent({ name: 'bad.txt', type: 'text/plain', size: 10 })); expect(c.attachmentError()).toContain('PDF, JPG, PNG or WEBP');
    c.selectAttachment(fileEvent({ name: 'large.pdf', type: 'application/pdf', size: 15 * 1024 * 1024 + 1 })); expect(c.attachmentError()).toContain('15 MB');
    c.clinicalRecord.set({ ...clinicalRecord(), attachments: Array.from({ length: 5 }, (_, i) => attachment(`SC-CLA-${i}`)) }); c.selectAttachment(fileEvent({ name: 'sixth.pdf', type: 'application/pdf', size: 100 })); expect(c.attachmentError()).toContain('maximum of 5');
    c.clinicalRecord.set({ ...clinicalRecord(), status: 'FINALIZED', finalizedAt: '2026-08-29T11:00:00Z' }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).not.toContain('Attach supporting clinical documents or images');
  });
  it('uploads a valid file and refetches without fabricating metadata', async () => { const { fixture, records } = await setup(); const c = fixture.componentInstance; const file = new File(['%PDF-'], 'result.pdf', { type: 'application/pdf' }); c.selectAttachment(fileEvent(file)); expect(c.selectedFile()?.name).toBe('result.pdf'); c.uploadSelectedAttachment(); expect(records.uploadAttachment).toHaveBeenCalledWith('SC-CLR-1', file); expect(records.getForProviderAppointment).toHaveBeenCalledTimes(2); });
  it('preserves the record and shows safe feedback when upload fails', async () => { const { fixture, records } = await setup(); records.uploadAttachment.mockReturnValue(throwError(() => ({ status: 500 }))); const c = fixture.componentInstance; c.selectAttachment(fileEvent(new File(['x'], 'image.png', { type: 'image/png' }))); c.uploadSelectedAttachment(); expect(c.clinicalRecord()?.reference).toBe('SC-CLR-1'); expect(c.attachmentError()).toContain('could not upload'); });
  it('requires delete confirmation, refetches after deletion, and hides delete when finalized', async () => { const withFile = { ...clinicalRecord(), attachments: [attachment()] }; const { fixture, records } = await setup(withFile); const c = fixture.componentInstance; fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Delete'); c.attachmentToDelete.set(attachment()); fixture.detectChanges(); expect(fixture.nativeElement.querySelector('[role="alertdialog"]')).not.toBeNull(); c.deleteAttachment(attachment()); expect(records.deleteAttachment).toHaveBeenCalledWith('SC-CLR-1', 'SC-CLA-1'); expect(records.getForProviderAppointment).toHaveBeenCalledTimes(2); c.clinicalRecord.set({ ...withFile, status: 'FINALIZED', finalizedAt: '2026-08-29T11:00:00Z' }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).not.toContain('Delete'); });
  it('requests provider access only on view and clears an image preview URL on close', async () => { const withFile = { ...clinicalRecord(), attachments: [attachment()] }; const { fixture, records } = await setup(withFile); const c = fixture.componentInstance; expect(records.getProviderAttachmentAccess).not.toHaveBeenCalled(); expect(c.previewUrl()).toBeNull(); c.viewProviderAttachment(attachment()); expect(records.getProviderAttachmentAccess).toHaveBeenCalledWith('SC-CLR-1', 'SC-CLA-1'); expect(c.previewUrl()).toBe('https://files.example.test/file'); c.closePreview(); expect(c.previewUrl()).toBeNull(); });
  it('formats safe attachment metadata', async () => { const { fixture } = await setup({ ...clinicalRecord(), attachments: [attachment()] }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('scan.png'); expect(fixture.nativeElement.textContent).toContain('1 KB'); });
});
function appointment(status: 'SCHEDULED' | 'CONFIRMED' | 'IN_PROGRESS' = 'IN_PROGRESS') { return { appointmentReference: 'SC-APT-1', careRequestReference: 'SC-CARE-1', status, deliveryMode: 'IN_PERSON' as const, service: { code: 'GENERAL_CONSULTATION', name: 'General Consultation' }, provider: { providerReference: 'SCPR-1', displayName: 'Clinic', providerType: 'CLINIC' }, providerLocation: null, scheduledDate: '2026-08-29', scheduledTimeFrom: '10:00', scheduledTimeTo: '10:30', timezone: 'Africa/Lagos', notes: null, meetingUrl: null, createdAt: '2026-08-29T08:00:00Z', updatedAt: '2026-08-29T08:00:00Z' }; }
function clinicalRecord(recordType: 'CONSULTATION' | 'LAB_RESULT' = 'CONSULTATION'): ClinicalRecord { return { reference: 'SC-CLR-1', recordType, title: 'Consultation outcome', summary: null, status: 'DRAFT', occurredAt: '2026-08-29T10:00:00Z', finalizedAt: null, provider: { providerReference: 'SCPR-1', displayName: 'Clinic', providerType: 'CLINIC' }, careRequestReference: 'SC-CARE-1', careAppointmentReference: 'SC-APT-1', service: { code: 'GENERAL_CONSULTATION', name: 'General Consultation' }, consultation: recordType === 'CONSULTATION' ? { presentingComplaint: null, historyOfPresentingComplaint: null, observations: null, assessment: null, diagnosis: 'Assessment', plan: null, followUpInstructions: null } : null, documentation: recordType === 'LAB_RESULT' ? { schemaVersion: 1, source: 'SYSTEM_DEFAULT', providerTemplateVersion: null, fields: [{ key: 'resultSummary', label: 'Result summary', type: 'TEXTAREA', required: true, core: true, sortOrder: 1 }] } : null, structuredData: recordType === 'LAB_RESULT' ? { resultSummary: 'Draft value' } : null, attachments: [], createdAt: '2026-08-29T10:00:00Z', updatedAt: '2026-08-29T10:00:00Z' }; }
function attachment(reference = 'SC-CLA-1') { return { reference, originalName: 'scan.png', mimeType: 'image/png', sizeBytes: 1024, resourceType: 'IMAGE' as const, createdAt: '2026-08-29T10:30:00Z' }; }
function fileEvent(file: Pick<File, 'name' | 'type' | 'size'>): Event { return { target: { files: [file] } } as unknown as Event; }
