import { TestBed } from '@angular/core/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { of, throwError } from 'rxjs';
import { ClinicalRecordsApiService } from '../../core/services/clinical-records-api.service';
import { ProviderCareOperationsApiService } from '../../core/services/provider-care-operations-api.service';
import { ProviderCareServicesApiService } from '../../core/services/provider-care-services-api.service';
import { ProviderCareAppointmentDetailPageComponent } from './provider-care-appointment-detail-page.component';

describe('ProviderCareAppointmentDetailPageComponent clinical records', () => {
  async function setup(record: ReturnType<typeof clinicalRecord> | null = null, type: string | null = 'CONSULTATION') {
    const operations = { getAppointment: vi.fn(() => of(appointment())), completeAppointment: vi.fn(() => of(appointment())), startAppointment: vi.fn(), markNoShow: vi.fn(), cancelAppointment: vi.fn(), updateMeetingLink: vi.fn() };
    const careServices = { getCatalogue: vi.fn(() => of([{ id: 'definition', code: 'GENERAL_CONSULTATION', name: 'General Consultation', description: null, isActive: true, clinicalRecordType: type }])) };
    const records = { getForProviderAppointment: vi.fn((_reference: string) => record ? of(record) : throwError(() => ({ status: 404 }))), createForProviderAppointment: vi.fn((_reference: string, _body: unknown) => of(clinicalRecord())), updateForProviderAppointment: vi.fn((_reference: string, _body: unknown) => of(clinicalRecord())), finalizeForProviderAppointment: vi.fn((_reference: string) => of({ ...clinicalRecord(), status: 'FINALIZED' })) };
    await TestBed.configureTestingModule({ imports: [ProviderCareAppointmentDetailPageComponent], providers: [provideRouter([]), { provide: ActivatedRoute, useValue: { snapshot: { paramMap: { get: () => 'SC-APT-1' } } } }, { provide: ProviderCareOperationsApiService, useValue: operations }, { provide: ProviderCareServicesApiService, useValue: careServices }, { provide: ClinicalRecordsApiService, useValue: records }] }).compileComponents();
    const fixture = TestBed.createComponent(ProviderCareAppointmentDetailPageComponent); fixture.detectChanges();
    return { fixture, operations, records };
  }
  it('shows create state and blocks completion when the required record is absent', async () => { const { fixture } = await setup(); const c = fixture.componentInstance; expect(fixture.nativeElement.textContent).toContain('Create consultation record'); expect(c.completionBlockMessage()).toContain('Complete the required clinical record'); });
  it('creates a consultation record without identity or ownership fields', async () => { const { fixture, records } = await setup(); const c = fixture.componentInstance; c.openRecordForm(); c.recordForm.patchValue({ title: 'Consultation outcome', diagnosis: 'Assessment' }); c.saveClinicalRecord(); const body = records.createForProviderAppointment.mock.calls[0][1]; expect(body).toMatchObject({ recordType: 'CONSULTATION', title: 'Consultation outcome', consultation: { diagnosis: 'Assessment' } }); expect(body).not.toHaveProperty('patientId'); expect(body).not.toHaveProperty('providerId'); });
  it('populates and updates a draft, then requires finalization', async () => { const { fixture, records } = await setup(clinicalRecord()); const c = fixture.componentInstance; c.openRecordForm(); expect(c.recordForm.controls.diagnosis.value).toBe('Assessment'); c.recordForm.controls.diagnosis.setValue('Updated'); c.saveClinicalRecord(); expect(records.updateForProviderAppointment).toHaveBeenCalled(); expect(c.completionBlockMessage()).toContain('Finalize'); });
  it('finalizes only after confirmation and makes a finalized record read-only', async () => { const { fixture, records } = await setup(clinicalRecord()); const c = fixture.componentInstance; c.finalizeOpen.set(true); fixture.detectChanges(); expect(fixture.nativeElement.querySelector('[role="alertdialog"]')).not.toBeNull(); c.finalizeClinicalRecord(); expect(records.finalizeForProviderAppointment).toHaveBeenCalledWith('SC-APT-1'); c.clinicalRecord.set({ ...clinicalRecord(), status: 'FINALIZED', finalizedAt: '2026-08-29T09:00:00Z' }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).not.toContain('Edit clinical record'); expect(c.completionBlockMessage()).toBeNull(); });
  it('shows a safe placeholder for unsupported structured types', async () => { const { fixture } = await setup(null, 'LAB_RESULT'); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('Structured entry for this record type is not available yet'); });
});
function appointment() { return { appointmentReference: 'SC-APT-1', careRequestReference: 'SC-CARE-1', status: 'IN_PROGRESS' as const, deliveryMode: 'IN_PERSON' as const, service: { code: 'GENERAL_CONSULTATION', name: 'General Consultation' }, provider: { providerReference: 'SCPR-1', displayName: 'Clinic', providerType: 'CLINIC' }, providerLocation: null, scheduledDate: '2026-08-29', scheduledTimeFrom: '10:00', scheduledTimeTo: '10:30', timezone: 'Africa/Lagos', notes: null, meetingUrl: null, createdAt: '2026-08-29T08:00:00Z', updatedAt: '2026-08-29T08:00:00Z' }; }
function clinicalRecord() { return { reference: 'SC-CLR-1', recordType: 'CONSULTATION' as const, title: 'Consultation outcome', summary: null, status: 'DRAFT' as const, occurredAt: '2026-08-29T10:00:00Z', finalizedAt: null, provider: { providerReference: 'SCPR-1', displayName: 'Clinic', providerType: 'CLINIC' }, careRequestReference: 'SC-CARE-1', careAppointmentReference: 'SC-APT-1', service: { code: 'GENERAL_CONSULTATION', name: 'General Consultation' }, consultation: { presentingComplaint: null, historyOfPresentingComplaint: null, observations: null, assessment: null, diagnosis: 'Assessment', plan: null, followUpInstructions: null }, createdAt: '2026-08-29T10:00:00Z', updatedAt: '2026-08-29T10:00:00Z' }; }
