import { ChangeDetectionStrategy,Component,inject,input,output,signal } from '@angular/core';import { ClinicalDecisionSupportInput,ClinicalDiagnosisSuggestion,ClinicalSuggestionItem } from '../core/models/clinical-decision-support.model';import { ClinicalDecisionSupportApiService } from '../core/services/clinical-decision-support-api.service';import { finalize } from 'rxjs';
@Component({selector:'app-clinical-smart-suggestions',changeDetection:ChangeDetectionStrategy.OnPush,template:`
<section class="mt-5 rounded-2xl border border-brand-100 bg-brand-50/40 p-4">
<div class="flex flex-wrap items-center justify-between gap-3"><div><h3 class="font-black text-brand-950">Smart suggestions</h3><p class="text-sm text-slate-600">Optional clinical decision support. Nothing is added or issued until you choose it.</p></div><button type="button" (click)="refresh()" [disabled]="loading()" class="rounded-xl border bg-white px-4 py-2 font-bold">{{loading()?'Checking…':'Check suggestions'}}</button></div>
@if(error()){<p class="mt-3 text-sm text-red-700">{{error()}}</p>}
@if(redFlags().length){<div class="mt-4 rounded-xl bg-red-50 p-4 text-red-900"><strong>Potential red flags in the note</strong><p class="mt-1 text-sm">{{redFlags().join(' · ')}}. Review urgency and the patient clinically.</p></div>}
@if(diagnoses().length){<div class="mt-4 grid gap-3">@for(d of diagnoses();track d.code){<article class="rounded-xl border bg-white p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><strong>{{d.diagnosisName}}</strong><p class="mt-1 text-xs text-slate-500">{{d.reason}}</p></div><button type="button" (click)="diagnosisChosen.emit(d.diagnosisName)" class="rounded-lg bg-brand-700 px-3 py-2 text-sm font-bold text-white">Use diagnosis</button></div>@if(d.clinicalNote){<p class="mt-2 text-sm text-slate-600">{{d.clinicalNote}}</p>}<div class="mt-3 flex flex-wrap gap-2">@for(i of combined(d);track i.code){<button type="button" (click)="itemChosen.emit(i)" class="rounded-full border px-3 py-2 text-sm font-bold">+ {{i.name}}</button>}@for(r of d.referrals;track r){<button type="button" (click)="referralChosen.emit(r)" class="rounded-full border px-3 py-2 text-sm font-bold">+ Refer {{r}}</button>}</div></article>}</div>} @else if(checked()&&!loading()){<p class="mt-3 text-sm text-slate-600">No configured suggestion matched. Continue with your clinical assessment or search the full catalogues.</p>}
</section>`})
export class ClinicalSmartSuggestionsComponent{private api=inject(ClinicalDecisionSupportApiService);readonly context=input.required<ClinicalDecisionSupportInput>();readonly diagnosisChosen=output<string>();readonly itemChosen=output<ClinicalSuggestionItem>();readonly referralChosen=output<string>();readonly loading=signal(false);readonly checked=signal(false);readonly error=signal('');readonly diagnoses=signal<readonly ClinicalDiagnosisSuggestion[]>([]);readonly redFlags=signal<readonly string[]>([]);refresh(){this.loading.set(true);this.error.set('');this.api.suggest(this.context()).pipe(finalize(()=>{this.loading.set(false);this.checked.set(true)})).subscribe({next:r=>{this.diagnoses.set(r.diagnoses);this.redFlags.set(r.redFlags)},error:()=>this.error.set('Suggestions could not be loaded. Your clinical documentation is unaffected.')})}combined(d:ClinicalDiagnosisSuggestion){return [...d.labs,...d.imaging,...d.medications]}}
