import { PublicBookingFundingAttemptStatus } from './public-booking.model';

export type PatientProviderConnectionType = 'NEW_PATIENT_REGISTRATION' | 'EXISTING_PATIENT_LINK';
export type PatientProviderConnectionStatus = 'AWAITING_FUNDING' | 'SUBMITTED' | 'UNABLE_TO_VERIFY' | 'CONNECTED' | 'REJECTED' | 'CANCELLED';
export type PatientProviderConnectionFundingPurpose = 'INITIAL' | 'CONVERSION_ADDITIONAL';
export type PatientProviderConnectionFundingStatus = 'PENDING' | 'PAID' | 'SATISFIED_FREE';
export interface PatientProviderConnectionProvider { readonly providerReference:string; readonly displayName:string; readonly providerType:string; readonly location:{readonly city:string|null;readonly stateOrRegion:string|null;readonly countryCode:string|null}; }
export interface PatientProviderConnectionPath { readonly enabled:boolean; readonly feeMinor:number|null; readonly currency:string|null; }
export interface PatientProviderConnectionDirectoryItem extends PatientProviderConnectionProvider { readonly newPatientRegistration:PatientProviderConnectionPath; readonly existingPatientLink:PatientProviderConnectionPath; }
export interface PatientProviderConnectionFundingItem { readonly purpose:PatientProviderConnectionFundingPurpose; readonly amountMinor:number; readonly currency:string; readonly status:PatientProviderConnectionFundingStatus; readonly paidAt:string|null; }
export interface PatientProviderConnection { readonly reference:string; readonly provider:PatientProviderConnectionProvider; readonly originalIntent:PatientProviderConnectionType; readonly currentPath:PatientProviderConnectionType; readonly status:PatientProviderConnectionStatus; readonly funding:readonly PatientProviderConnectionFundingItem[]; readonly externalPatientReference:string|null; readonly consentCapturedAt:string; readonly conversionRequestedAt:string|null; readonly connectedAt:string|null; readonly createdAt:string; readonly updatedAt:string; }
export interface ProviderPatientConnection extends PatientProviderConnection { readonly patient:{readonly patientReference:string;readonly givenName:string;readonly familyName:string;readonly dateOfBirth:string;readonly phone:string|null;readonly email:string|null}; readonly claimedExternalPatientReference:string|null; readonly originatedAsExistingPatientAttempt:boolean; }
export interface PatientProviderConnectionPage<T> { readonly items:readonly T[]; readonly page:number; readonly limit:number; readonly total:number; readonly totalPages:number; }
export interface PatientProviderConnectionConfiguration { readonly newPatientRegistration:PatientProviderConnectionPath; readonly existingPatientLink:PatientProviderConnectionPath; }
export interface UpdatePatientProviderConnectionConfiguration { readonly newPatientRegistrationEnabled:boolean; readonly newPatientRegistrationFeeMinor:number|null; readonly newPatientRegistrationCurrency:string|null; readonly existingPatientLinkEnabled:boolean; readonly existingPatientLinkFeeMinor:number|null; readonly existingPatientLinkCurrency:string|null; }
export interface PatientProviderConnectionFundingAttempt { readonly connectionReference:string; readonly purpose:PatientProviderConnectionFundingPurpose; readonly amountMinor:number; readonly currency:string; readonly fundingStatus:PatientProviderConnectionFundingStatus; readonly paid:boolean; readonly paymentAttemptStatus:PublicBookingFundingAttemptStatus|null; readonly paymentReference:string|null; readonly checkoutUrl:string|null; readonly accessCode:string|null; readonly paidAt:string|null; }
export interface PatientProviderConnectionFundingResponse { readonly connectionReference:string; readonly status:PatientProviderConnectionStatus; readonly fundings:readonly PatientProviderConnectionFundingAttempt[]; readonly fundingSatisfied:boolean; }
export interface StartNewPatientRegistrationRequest { readonly providerReference:string; readonly consentAcknowledged:boolean; }
export interface StartExistingPatientLinkRequest extends StartNewPatientRegistrationRequest { readonly externalPatientReference:string; }
export interface ProviderConnectionDecisionRequest { readonly externalPatientReference?:string; readonly reason?:string; }
