export type ProviderEarningStatus = 'HELD' | 'PAYABLE' | 'SETTLED' | 'VOIDED';
export type ProviderEarningSourceType = 'HEALTH_CHECK' | 'GENERAL_CARE' | 'PHARMACY_FULFILLMENT' | 'PATIENT_REGISTRATION' | 'PATIENT_LINKING';
export interface ProviderEarningBreakdown { readonly key: string; readonly earningCount: number; readonly grossAmountMinor: number; readonly commissionAmountMinor: number; readonly providerShareMinor: number; }
export interface ProviderEarningCurrencySummary { readonly currency: string; readonly earningCount: number; readonly grossAmountMinor: number; readonly commissionAmountMinor: number; readonly providerShareMinor: number; readonly heldAmountMinor: number; readonly payableAmountMinor: number; readonly settledAmountMinor: number; readonly voidedAmountMinor: number; readonly statusBreakdown: readonly ProviderEarningBreakdown[]; readonly sourceBreakdown: readonly ProviderEarningBreakdown[]; }
export interface ProviderEarning { readonly reference: string; readonly sourceType: ProviderEarningSourceType; readonly sourceReference: string; readonly currency: string; readonly grossAmountMinor: number; readonly commissionBasisPoints: number; readonly commissionSource: string; readonly commissionAmountMinor: number; readonly providerShareMinor: number; readonly status: ProviderEarningStatus; readonly payableAt: string | null; readonly settledAt: string | null; readonly createdAt: string; readonly updatedAt: string; }
export interface AdminProviderEarning extends ProviderEarning { readonly provider: { readonly reference: string; readonly displayName: string }; }
export interface ProviderEarningPage<T extends ProviderEarning = ProviderEarning> { readonly items: readonly T[]; readonly page: number; readonly limit: number; readonly total: number; readonly totalPages: number; }
export interface ProviderEarningFilters { readonly status?: ProviderEarningStatus; readonly sourceType?: ProviderEarningSourceType; readonly currency?: string; readonly from?: string; readonly to?: string; readonly page?: number; readonly limit?: number; }
export interface AdminProviderEarningFilters extends ProviderEarningFilters { readonly providerReference?: string; }
