import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { PatientProviderConnectionDirectoryItem, PatientProviderConnectionType } from '../../core/models/patient-provider-connection.model';
import { PatientProviderConnectionsApiService } from '../../core/services/patient-provider-connections-api.service';
import { formatMinor } from '../provider/care-money';

@Component({
  selector: 'app-connect-provider-page', imports: [ReactiveFormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<main class="mx-auto max-w-4xl px-5 py-10 sm:px-8"><a [routerLink]="backUrl()" class="font-bold text-brand-700 underline">← Back</a>
  <h1 class="mt-5 text-3xl font-bold">{{targeted() && selected() ? 'Connect with ' + selected()?.displayName : 'Connect to a Provider'}}</h1>
  @if(targeted() && loading()){<p role="status" class="mt-8 rounded-2xl border bg-white p-6">Preparing this Provider connection…</p>}
  @else if(targeted() && targetError()){<section role="alert" class="mt-8 rounded-2xl bg-red-50 p-6"><h2 class="font-bold">This Provider is unavailable</h2><p class="mt-2">We couldn't prepare this Provider connection. Return to the access request and try again.</p><a [routerLink]="backUrl()" class="mt-4 inline-flex rounded-xl border px-4 py-2 font-bold">Back to access requests</a></section>}
  @else if(!targeted() && !selected()){<section class="mt-8 rounded-2xl border bg-white p-6"><div class="flex gap-3"><label class="flex-1"><span class="sr-only">Search Providers</span><input [formControl]="search" maxlength="120" placeholder="Search Providers by name" class="w-full rounded-xl border p-3"></label><button type="button" (click)="load(1)" class="rounded-xl border px-5 font-bold">Search</button></div>@if(loading()){<p role="status" class="mt-4">Loading Providers…</p>}@else if(directoryError()){<p role="alert" class="mt-4 rounded-xl bg-red-50 p-4">Unable to load Providers. <button type="button" (click)="load(page())" class="font-bold underline">Try again</button></p>}@else if(!providers().length){<p class="mt-4 rounded-xl bg-slate-50 p-4">No Providers match this search.</p>}@else{<div class="mt-5 grid gap-3">@for(p of providers();track p.providerReference){<button type="button" (click)="choose(p)" class="rounded-xl border p-4 text-left"><span class="block font-bold">{{p.displayName}}</span><span class="block text-sm text-slate-600">{{p.providerType}} · {{location(p)}}</span>@if(p.newPatientRegistration.enabled){<span class="mt-2 block">New registration: {{money(p.newPatientRegistration.feeMinor,p.newPatientRegistration.currency)}}</span>}@if(p.existingPatientLink.enabled){<span class="block">Existing patient link: {{money(p.existingPatientLink.feeMinor,p.existingPatientLink.currency)}}</span>}</button>}</div><div class="mt-4 flex justify-between"><button type="button" (click)="load(page()-1)" [disabled]="page()<=1">Previous</button><span>Page {{page()}} of {{pages()||1}}</span><button type="button" (click)="load(page()+1)" [disabled]="page()>=pages()">Next</button></div>}</section>}
  @else if(selected();as p){<form [formGroup]="form" (ngSubmit)="submit()" class="mt-8 grid gap-6 rounded-2xl border bg-white p-6"><div><p class="text-sm font-bold uppercase text-brand-600">Selected Provider</p><h2 class="text-2xl font-bold">{{p.displayName}}</h2><p class="text-sm text-slate-600">{{p.providerType}} · {{location(p)}}</p>@if(!targeted()){<button type="button" (click)="selected.set(null)" class="mt-2 font-bold underline">Change Provider</button>}</div><fieldset class="grid gap-3"><legend class="font-bold">Do you already have a patient record with this Provider?</legend>@if(p.newPatientRegistration.enabled){<label class="rounded-xl border p-4"><input type="radio" formControlName="path" value="NEW_PATIENT_REGISTRATION"> <strong>I am a new patient</strong><span class="block pl-6">Register me with this Provider · {{money(p.newPatientRegistration.feeMinor,p.newPatientRegistration.currency)}}</span></label>}@if(p.existingPatientLink.enabled){<label class="rounded-xl border p-4"><input type="radio" formControlName="path" value="EXISTING_PATIENT_LINK"> <strong>I already have a patient record</strong><span class="block pl-6">Connect my existing Provider patient number · {{money(p.existingPatientLink.feeMinor,p.existingPatientLink.currency)}}</span></label>}</fieldset>@if(form.controls.path.value==='EXISTING_PATIENT_LINK'){<label class="grid gap-2 font-bold">Provider Patient Number<input formControlName="externalPatientReference" maxlength="160" class="rounded-xl border p-3"><span class="text-sm font-normal text-slate-600">The Provider will verify this information. Entering it does not prove identity.</span></label>}<label class="flex gap-3"><input type="checkbox" formControlName="consentAcknowledged"><span>I authorize SmartClinic to send the required registration and identity information to this Provider.</span></label>@if(error()){<p role="alert" class="rounded-xl bg-red-50 p-4">{{error()}}</p>}<button type="submit" [disabled]="saving()" class="rounded-xl bg-brand-700 px-5 py-3 font-bold text-white">{{saving()?'Submitting…':'Continue'}}</button></form>}</main>`,
})
export class ConnectProviderPageComponent {
  private readonly api=inject(PatientProviderConnectionsApiService); private readonly router=inject(Router); private readonly route=inject(ActivatedRoute);
  readonly search=new FormControl('',{nonNullable:true}); readonly providers=signal<readonly PatientProviderConnectionDirectoryItem[]>([]); readonly selected=signal<PatientProviderConnectionDirectoryItem|null>(null); readonly loading=signal(false); readonly directoryError=signal(false); readonly targetError=signal(false); readonly page=signal(1); readonly pages=signal(0); readonly saving=signal(false); readonly error=signal('');
  readonly providerReference=this.route.snapshot.queryParamMap.get('providerReference'); readonly targeted=signal(this.providerReference!==null); readonly returnUrl=this.safeReturnUrl(this.route.snapshot.queryParamMap.get('returnUrl'));
  readonly form=new FormGroup({path:new FormControl<PatientProviderConnectionType|null>(null,Validators.required),externalPatientReference:new FormControl('',{nonNullable:true}),consentAcknowledged:new FormControl(false,{nonNullable:true,validators:[Validators.requiredTrue]})});
  constructor(){if(this.providerReference)this.loadTarget(this.providerReference);else this.load(1);}
  load(page:number){if(page<1||this.loading()||this.targeted())return;this.loading.set(true);this.directoryError.set(false);this.api.directory(this.search.value,page,10).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{this.providers.set(r.items);this.page.set(r.page);this.pages.set(r.totalPages)},error:()=>this.directoryError.set(true)});}
  private loadTarget(reference:string){if(!/^SCPR-[A-F0-9]{32}$/.test(reference)){this.targetError.set(true);return;}this.loading.set(true);this.api.listMine(1,100).subscribe({next:connections=>{const existing=connections.items.find(item=>item.provider.providerReference===reference);if(existing&&!['REJECTED','CANCELLED'].includes(existing.status)){if(existing.status==='CONNECTED'&&this.returnUrl){void this.router.navigateByUrl(this.returnUrl);return;}void this.router.navigate(['/me/providers',existing.reference],{queryParams:this.returnUrl?{returnUrl:this.returnUrl}:undefined});return;}this.resolveTarget(reference,1);},error:()=>{this.loading.set(false);this.targetError.set(true);}});}
  private resolveTarget(reference:string,page:number){this.api.directory('',page,100).subscribe({next:r=>{const exact=r.items.find(item=>item.providerReference===reference);if(exact){this.choose(exact);this.loading.set(false);}else if(page<r.totalPages)this.resolveTarget(reference,page+1);else{this.loading.set(false);this.targetError.set(true);}},error:()=>{this.loading.set(false);this.targetError.set(true);}});}
  choose(p:PatientProviderConnectionDirectoryItem){this.selected.set(p);const path=p.newPatientRegistration.enabled?'NEW_PATIENT_REGISTRATION':'EXISTING_PATIENT_LINK';this.form.patchValue({path});}
  submit(){const p=this.selected(),path=this.form.controls.path.value;this.error.set('');if(!p||this.form.invalid||(path==='EXISTING_PATIENT_LINK'&&!this.form.controls.externalPatientReference.value.trim())){this.form.markAllAsTouched();this.error.set('Complete the required details and consent before continuing.');return;}this.saving.set(true);const call=path==='NEW_PATIENT_REGISTRATION'?this.api.startNew({providerReference:p.providerReference,consentAcknowledged:true}):this.api.startExisting({providerReference:p.providerReference,consentAcknowledged:true,externalPatientReference:this.form.controls.externalPatientReference.value.trim()});call.pipe(finalize(()=>this.saving.set(false))).subscribe({next:c=>this.router.navigate(['/me/providers',c.reference],{queryParams:this.returnUrl?{returnUrl:this.returnUrl}:undefined}),error:()=>this.error.set('Unable to start this Provider connection. Please try again.')});}
  backUrl(){return this.returnUrl||'/me/providers';} private safeReturnUrl(value:string|null){return value?.startsWith('/me/')&&!value.startsWith('//')?value:null;} money(v:number|null,c:string|null){return v==null||!c?'Unavailable':formatMinor(v,c);} location(p:PatientProviderConnectionDirectoryItem){return[p.location.city,p.location.stateOrRegion,p.location.countryCode].filter(Boolean).join(', ');}
}
