import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AdminRewardWithdrawalDetail } from '../../core/models/reward-withdrawal.model';
import { RewardWithdrawalsApiService } from '../../core/services/reward-withdrawals-api.service';
import { UtilsService } from '../../core/services/utils.service';
type Action='PROCESSING'|'PAID'|'FAILED'|'CANCELLED';
@Component({selector:'app-admin-reward-withdrawal-detail-page',imports:[ReactiveFormsModule,RouterLink],changeDetection:ChangeDetectionStrategy.OnPush,
template:`<main class="mx-auto max-w-5xl px-5 py-10 sm:px-8"><a routerLink="/admin/reward-withdrawals" class="font-bold text-brand-700 underline">← Reward withdrawals</a>@if(loading()){<p role="status" class="mt-6 rounded-xl bg-brand-50 p-5">Loading withdrawal details…</p>}@if(error()){<div role="alert" class="mt-6 rounded-xl bg-red-50 p-5 text-red-900"><p>{{error()}}</p><button (click)="load()" class="mt-3 rounded-lg border px-4 py-2 font-bold">Try again</button></div>}@if(item();as w){<header class="mt-6"><p class="text-sm font-bold uppercase text-brand-600">Sensitive financial information</p><h1 class="mt-2 text-3xl font-bold text-brand-900">Withdrawal {{w.withdrawalReference}}</h1><p class="mt-2"><span class="rounded-full bg-slate-100 px-3 py-1 font-semibold">{{label(w.status)}}</span></p></header>
<div class="mt-7 grid gap-5 lg:grid-cols-2"><section class="rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">Request</h2><dl class="mt-4 grid gap-3"><div><dt class="text-sm text-slate-500">User</dt><dd>{{w.user?.displayName||'—'}} · {{w.user?.email||'—'}}</dd></div><div><dt class="text-sm text-slate-500">Points</dt><dd>{{w.points}}</dd></div><div><dt class="text-sm text-slate-500">Amount</dt><dd>{{utils.formatMoney(w.amount,w.currency)}}</dd></div><div><dt class="text-sm text-slate-500">Rate used</dt><dd>{{w.conversionRate.points}} points = {{utils.formatMoney(w.conversionRate.amount,w.currency)}}</dd></div><div><dt class="text-sm text-slate-500">Requested</dt><dd>{{utils.formatDateTime(w.requestedAt)}}</dd></div></dl></section><section class="rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 class="text-xl font-bold">Bank details</h2><dl class="mt-4 grid gap-3"><div><dt class="text-sm text-slate-600">Bank</dt><dd class="font-semibold">{{w.bankName}}</dd></div><div><dt class="text-sm text-slate-600">Account number</dt><dd class="font-mono text-lg font-bold">{{w.accountNumber}}</dd></div><div><dt class="text-sm text-slate-600">Account name</dt><dd>{{w.accountName}}</dd></div></dl><p class="mt-5 text-sm">Make the transfer using your approved banking channel, then return here to update the withdrawal status. SmartClinic does not send this transfer automatically.</p></section></div>
<section class="mt-6 rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">Processing</h2><dl class="mt-4 grid gap-3 sm:grid-cols-2"><div><dt class="text-sm text-slate-500">Processing time</dt><dd>{{utils.formatDateTime(w.processingAt)}}</dd></div><div><dt class="text-sm text-slate-500">Paid time</dt><dd>{{utils.formatDateTime(w.paidAt)}}</dd></div><div><dt class="text-sm text-slate-500">External transfer reference</dt><dd>{{w.externalReference||'—'}}</dd></div><div><dt class="text-sm text-slate-500">Admin note</dt><dd>{{w.adminNote||'—'}}</dd></div></dl>@if(w.status==='REQUESTED'||w.status==='PROCESSING'){<div class="mt-6 flex flex-wrap gap-3">@if(w.status==='REQUESTED'){<button (click)="open('PROCESSING')" class="rounded-lg border border-brand-700 px-4 py-2 font-bold text-brand-700">Mark processing</button>}<button (click)="open('PAID')" class="rounded-lg bg-brand-700 px-4 py-2 font-bold text-white">Mark paid</button><button (click)="open('FAILED')" class="rounded-lg border border-red-700 px-4 py-2 font-bold text-red-700">Mark failed</button><button (click)="open('CANCELLED')" class="rounded-lg border border-red-700 px-4 py-2 font-bold text-red-700">Cancel request</button></div>}</section>
<section class="mt-6 rounded-2xl border bg-white p-6"><h2 class="text-xl font-bold">Status history</h2><ol class="mt-4 grid gap-3">@for(h of w.history;track h.createdAt){<li class="border-l-4 border-brand-200 pl-4"><strong>{{label(h.toStatus)}}</strong><span class="ml-2 text-sm text-slate-500">{{utils.formatDateTime(h.createdAt)}}</span>@if(h.reasonNote){<p class="mt-1">{{h.reasonNote}}</p>}</li>}</ol></section>}
@if(action();as a){<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="alertdialog" aria-modal="true" aria-labelledby="withdrawal-action-title" class="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-xl"><h2 id="withdrawal-action-title" class="text-2xl font-bold">{{title(a)}}</h2><p class="mt-3">{{explanation(a)}}</p><form [formGroup]="actionForm" (ngSubmit)="confirm()" class="mt-5 grid gap-4">@if(a==='PAID'){<label class="font-semibold">External transfer reference<input formControlName="externalReference" placeholder="e.g. BANK-TXN-123456" class="mt-1 w-full rounded-lg border p-3"></label><label class="font-semibold">Admin note (optional)<textarea formControlName="note" placeholder="e.g. Transferred manually via mobile banking" class="mt-1 w-full rounded-lg border p-3"></textarea></label>}@if(a==='FAILED'||a==='CANCELLED'){<label class="font-semibold">Reason<textarea formControlName="reason" placeholder="Enter a reason…" class="mt-1 w-full rounded-lg border p-3"></textarea></label>}@if(actionError()){<p role="alert" class="rounded-lg bg-red-50 p-3 text-red-900">{{actionError()}}</p>}<div class="flex justify-end gap-3"><button type="button" (click)="close()" [disabled]="mutating()" class="rounded-lg border px-4 py-2 font-bold">Cancel</button><button type="submit" [disabled]="invalid(a)||mutating()" [class]="a==='FAILED'||a==='CANCELLED'?'rounded-lg bg-red-700 px-4 py-2 font-bold text-white disabled:opacity-50':'rounded-lg bg-brand-700 px-4 py-2 font-bold text-white disabled:opacity-50'">{{mutating()?'Updating…':'Confirm'}}</button></div></form></section></div>}</main>`})
export class AdminRewardWithdrawalDetailPageComponent{
 private readonly api=inject(RewardWithdrawalsApiService);private readonly route=inject(ActivatedRoute);private readonly fb=inject(FormBuilder);readonly utils=inject(UtilsService);readonly item=signal<AdminRewardWithdrawalDetail|null>(null);readonly loading=signal(false);readonly error=signal<string|null>(null);readonly action=signal<Action|null>(null);readonly mutating=signal(false);readonly actionError=signal<string|null>(null);readonly actionForm=this.fb.nonNullable.group({externalReference:[''],note:[''],reason:['']});private readonly reference=this.route.snapshot.paramMap.get('reference')??'';constructor(){this.load()}load(){this.loading.set(true);this.error.set(null);this.api.adminDetail(this.reference).pipe(finalize(()=>this.loading.set(false))).subscribe({next:v=>this.item.set(v),error:()=>this.error.set('We could not load this withdrawal.')})}open(a:Action){this.actionForm.reset();this.actionError.set(null);this.action.set(a)}close(){if(!this.mutating())this.action.set(null)}invalid(a:Action){return a==='PAID'?!this.actionForm.controls.externalReference.value.trim():a==='FAILED'||a==='CANCELLED'?!this.actionForm.controls.reason.value.trim():false}confirm(){const a=this.action();if(!a||this.invalid(a)||this.mutating())return;const f=this.actionForm.getRawValue();this.mutating.set(true);const call=a==='PROCESSING'?this.api.markProcessing(this.reference):a==='PAID'?this.api.markPaid(this.reference,f.externalReference.trim(),f.note.trim()||undefined):a==='FAILED'?this.api.markFailed(this.reference,f.reason.trim()):this.api.adminCancel(this.reference,f.reason.trim());call.pipe(finalize(()=>this.mutating.set(false))).subscribe({next:()=>{this.action.set(null);this.load()},error:()=>this.actionError.set('We could not update this withdrawal. Its status may have changed; refresh and try again.')})}label(s:string){return s.charAt(0)+s.slice(1).toLowerCase()}title(a:Action){return ({PROCESSING:'Mark this withdrawal as processing?',PAID:'Confirm withdrawal paid',FAILED:'Mark this withdrawal as failed?',CANCELLED:'Cancel this withdrawal request?'} as const)[a]}explanation(a:Action){return ({PROCESSING:'Use this when you are about to make the manual bank transfer.',PAID:'Confirm only after the transfer has actually been completed.',FAILED:"Reserved points will return to the user's available balance.",CANCELLED:"Reserved points will return to the user's available balance."} as const)[a]}
}
