import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AdminRewardWithdrawal, RewardWithdrawalStatus } from '../../core/models/reward-withdrawal.model';
import { RewardWithdrawalsApiService } from '../../core/services/reward-withdrawals-api.service';
import { UtilsService } from '../../core/services/utils.service';

@Component({ selector:'app-admin-reward-withdrawals-page', imports:[ReactiveFormsModule,RouterLink], changeDetection:ChangeDetectionStrategy.OnPush,
template:`<main class="mx-auto max-w-7xl px-5 py-10 sm:px-8"><p class="text-sm font-bold uppercase tracking-wider text-brand-600">Operations</p><h1 class="mt-2 text-3xl font-bold text-brand-900">Reward Withdrawals</h1><p class="mt-2 text-slate-600">Review requests and record transfers completed through an approved external banking channel.</p>
<form [formGroup]="filters" (ngSubmit)="applyFilters()" class="mt-7 grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2 lg:grid-cols-5"><label class="font-semibold">Status<select formControlName="status" class="mt-1 w-full rounded-lg border p-3"><option value="">All statuses</option>@for(s of statuses;track s){<option [value]="s">{{label(s)}}</option>}</select></label><label class="font-semibold">Requested from<input type="date" formControlName="requestedFrom" class="mt-1 w-full rounded-lg border p-3"></label><label class="font-semibold">Requested to<input type="date" formControlName="requestedTo" class="mt-1 w-full rounded-lg border p-3"></label><label class="font-semibold">User email<input type="email" formControlName="userEmail" placeholder="e.g. ada@example.com" class="mt-1 w-full rounded-lg border p-3"></label><label class="font-semibold">Reference<input formControlName="reference" placeholder="e.g. SCW-2026-..." class="mt-1 w-full rounded-lg border p-3"></label><div class="sm:col-span-2 lg:col-span-5 flex gap-3"><button class="rounded-lg bg-brand-700 px-5 py-2 font-bold text-white">Apply filters</button><button type="button" (click)="clear()" class="rounded-lg border px-5 py-2 font-bold">Clear</button></div></form>
@if(loading()){<p role="status" class="mt-6 rounded-xl bg-brand-50 p-5">Loading reward withdrawals…</p>}@if(error()){<div role="alert" class="mt-6 rounded-xl bg-red-50 p-5 text-red-900"><p>{{error()}}</p><button (click)="load()" class="mt-3 rounded-lg border px-4 py-2 font-bold">Try again</button></div>}@if(!loading()&&!error()){@if(items().length){<div class="mt-6 overflow-x-auto rounded-2xl border bg-white"><table class="min-w-[860px] w-full text-left"><thead class="bg-slate-50"><tr><th class="p-4">Reference</th><th class="p-4">User</th><th class="p-4">Points</th><th class="p-4">Amount</th><th class="p-4">Status</th><th class="p-4">Requested</th><th class="p-4">Action</th></tr></thead><tbody>@for(item of items();track item.withdrawalReference){<tr class="border-t"><td class="p-4 font-semibold">{{item.withdrawalReference}}</td><td class="p-4"><span class="block">{{item.user?.displayName||'—'}}</span><span class="text-sm text-slate-500">{{item.user?.email||'—'}}</span></td><td class="p-4">{{item.points}}</td><td class="p-4">{{utils.formatMoney(item.amount,item.currency)}}</td><td class="p-4"><span class="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold">{{label(item.status)}}</span></td><td class="p-4">{{utils.formatDateTime(item.requestedAt)}}</td><td class="p-4"><a [routerLink]="['/admin/reward-withdrawals',item.withdrawalReference]" class="font-bold text-brand-700 underline">Review</a></td></tr>}</tbody></table></div><div class="mt-5 flex items-center justify-between"><button (click)="page(-1)" [disabled]="currentPage()<=1" class="rounded-lg border px-4 py-2 font-bold disabled:opacity-40">Previous</button><span>Page {{currentPage()}} of {{totalPages()||1}}</span><button (click)="page(1)" [disabled]="currentPage()>=totalPages()" class="rounded-lg border px-4 py-2 font-bold disabled:opacity-40">Next</button></div>}@else{<p class="mt-6 rounded-xl border bg-white p-6">No reward withdrawals match these filters.</p>}}</main>`})
export class AdminRewardWithdrawalsPageComponent{
 private readonly api=inject(RewardWithdrawalsApiService);private readonly fb=inject(FormBuilder);readonly utils=inject(UtilsService);readonly items=signal<AdminRewardWithdrawal[]>([]);readonly loading=signal(false);readonly error=signal<string|null>(null);readonly currentPage=signal(1);readonly totalPages=signal(0);readonly statuses:RewardWithdrawalStatus[]=['REQUESTED','PROCESSING','PAID','FAILED','CANCELLED'];readonly filters=this.fb.nonNullable.group({status:[''],requestedFrom:[''],requestedTo:[''],userEmail:[''],reference:['']});constructor(){this.load()}load(){this.loading.set(true);this.error.set(null);const f=this.filters.getRawValue();this.api.adminList({page:this.currentPage(),limit:20,...(f.status?{status:f.status as RewardWithdrawalStatus}:{}),...(f.requestedFrom?{requestedFrom:f.requestedFrom}:{}),...(f.requestedTo?{requestedTo:f.requestedTo}:{}),...(f.userEmail.trim()?{userEmail:f.userEmail.trim()}:{}),...(f.reference.trim()?{reference:f.reference.trim()}:{}),}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{this.items.set(r.items);this.totalPages.set(r.totalPages)},error:()=>this.error.set('We could not load reward withdrawals.')})}applyFilters(){this.currentPage.set(1);this.load()}clear(){this.filters.reset();this.currentPage.set(1);this.load()}page(delta:number){this.currentPage.update(v=>v+delta);this.load()}label(s:string){return s.charAt(0)+s.slice(1).toLowerCase()}
}
