import { HttpErrorResponse } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { AdminProviderPayoutAccount } from '../../core/models/provider-payout-account.model';
import { EligibleProviderEarning, ProviderPayoutSettlementMethod } from '../../core/models/provider-payout.model';
import { ProviderPayoutAccountsApiService } from '../../core/services/provider-payout-accounts-api.service';
import { ProviderPayoutsApiService } from '../../core/services/provider-payouts-api.service';
import { earningSourceLabel, formatEarningMoney } from '../provider/provider-earning-presentation';

@Component({ selector: 'app-admin-payout-create-page', imports: [ReactiveFormsModule, RouterLink], changeDetection: ChangeDetectionStrategy.OnPush, template: `
<main class="mx-auto max-w-6xl px-5 py-10 sm:px-8"><a routerLink="/admin/provider-payouts" class="font-bold text-brand-700 underline">← Payouts</a><h1 class="mt-5 text-3xl font-bold">Create payout</h1><p class="mt-2 text-slate-600">Select payable earnings for one Provider and currency. The backend determines the authoritative total.</p>
<form [formGroup]="form" (ngSubmit)="loadEligible(1,true)" class="mt-6 grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-2">
<label class="font-semibold">Provider reference<input formControlName="providerReference" placeholder="e.g. SCPR-..." class="mt-1 min-h-11 w-full rounded-lg border px-3"><span class="block text-xs font-normal">Use the Provider's public SmartClinic reference.</span></label>
<label class="font-semibold">Currency<input formControlName="currency" maxlength="3" placeholder="e.g. NGN" class="mt-1 min-h-11 w-full rounded-lg border px-3 uppercase"></label>
<label class="font-semibold">Settlement method<select formControlName="settlementMethod" class="mt-1 min-h-11 w-full rounded-lg border px-3"><option value="MANUAL_BANK_TRANSFER">Manual bank transfer</option><option value="MANUAL_OTHER">Other manual settlement</option></select></label>
<label class="font-semibold">Operational note (optional)<textarea formControlName="note" maxlength="1000" placeholder="e.g. August settlement batch" class="mt-1 w-full rounded-lg border p-3"></textarea></label>
@if(form.controls.settlementMethod.value==='MANUAL_BANK_TRANSFER'){<div class="sm:col-span-2"><label class="font-semibold">Payout destination (optional)<select formControlName="payoutAccountReference" class="mt-1 min-h-11 w-full rounded-lg border px-3"><option value="">Not recorded</option>@for(a of accounts();track a.reference){<option [value]="a.reference">{{a.bankName}} • {{a.maskedAccountNumber}} • {{a.accountName}}{{a.isDefault?' • Default':''}}</option>}</select></label><p class="mt-1 text-sm text-slate-600">Select the verified bank account intended for this manual settlement. SmartClinic records it for audit purposes; the transfer is completed manually outside SmartClinic.</p>@if(accountsLoading()){<p role="status" class="mt-2">Loading verified payout accounts…</p>}@else if(accountsError()){<p role="alert" class="mt-2 text-red-800">Verified payout accounts could not be loaded. You may continue without a recorded destination.</p>}@else if(accountContextReady()&&!accounts().length){<p class="mt-2">No verified payout account is available for this Provider in {{form.controls.currency.value.toUpperCase()}}. <a routerLink="/admin/provider-payout-accounts" class="font-bold underline">View payout accounts</a></p>}</div>}
<button [disabled]="form.invalid||eligibleLoading()" class="min-h-11 rounded-lg bg-brand-700 px-5 font-bold text-white disabled:opacity-50">{{eligibleLoading()?'Loading…':'Load eligible earnings'}}</button></form>
@if(eligibleError()){<div role="alert" class="mt-5 rounded-xl bg-red-50 p-4">{{eligibleError()}} <button type="button" (click)="loadEligible(page(),false)" class="font-bold underline">Refresh eligible earnings</button></div>}
@if(loaded()&&!eligibleLoading()){@if(!eligible().length){<p class="mt-6 rounded-xl border bg-white p-5">No eligible payable earnings were found.</p>}@else{<section class="mt-6"><h2 class="text-xl font-bold">Eligible earnings</h2><div class="mt-3 overflow-x-auto rounded-xl border bg-white"><table class="w-full min-w-[760px] text-left"><thead><tr><th class="p-3">Select</th><th class="p-3">Earning</th><th class="p-3">Source</th><th class="p-3">Provider share</th><th class="p-3">Payable</th></tr></thead><tbody>@for(e of eligible();track e.reference){<tr class="border-t"><td class="p-3"><input type="checkbox" [checked]="selected().has(e.reference)" (change)="toggle(e)" [attr.aria-label]="'Select '+e.reference"></td><td class="p-3">{{e.reference}}<span class="block text-xs">{{e.sourceReference}}</span></td><td class="p-3">{{source(e.sourceType)}}</td><td class="p-3">{{money(e.providerShareMinor,e.currency)}}</td><td class="p-3">{{e.payableAt?date(e.payableAt):'—'}}</td></tr>}</tbody></table></div><div class="mt-3 flex justify-between"><button (click)="loadEligible(page()-1,false)" [disabled]="page()<=1">Previous</button><span>Page {{page()}} of {{totalPages()||1}}</span><button (click)="loadEligible(page()+1,false)" [disabled]="page()>=totalPages()">Next</button></div></section>}
<aside class="sticky bottom-4 mt-6 rounded-2xl border bg-white p-5 shadow"><h2 class="text-lg font-bold">Payout summary</h2><dl class="mt-3 grid gap-2 sm:grid-cols-2"><div><dt>Provider</dt><dd>{{form.controls.providerReference.value}}</dd></div><div><dt>Currency</dt><dd>{{form.controls.currency.value.toUpperCase()}}</dd></div><div><dt>Selected earnings</dt><dd>{{selected().size}}</dd></div><div><dt>Preview amount</dt><dd class="font-bold">{{money(preview(),form.controls.currency.value.toUpperCase()||'NGN')}}</dd></div><div><dt>Settlement method</dt><dd>{{form.controls.settlementMethod.value==='MANUAL_BANK_TRANSFER'?'Manual bank transfer':'Other manual settlement'}}</dd></div><div><dt>Payout destination</dt><dd>@if(selectedAccount();as a){{{a.bankName}} · {{a.maskedAccountNumber}} · {{a.accountName}}}@else{Not recorded}</dd></div></dl><p class="mt-2 text-sm">Preview only — backend calculates the authoritative payout total. {{selectedAccount()?'The selected destination will be recorded as an immutable snapshot. Creating this payout does not send money.':'No payout destination will be recorded. Settlement can still be managed manually.'}}</p><button type="button" (click)="create()" [disabled]="!selected().size||creating()" class="mt-3 rounded-lg bg-brand-700 px-5 py-3 font-bold text-white disabled:opacity-50">{{creating()?'Creating…':'Create draft payout'}}</button>@if(createError()){<p role="alert" class="mt-3 text-red-800">{{createError()}}</p>}</aside>}</main>` })
export class AdminPayoutCreatePageComponent {
  private readonly api=inject(ProviderPayoutsApiService); private readonly accountsApi=inject(ProviderPayoutAccountsApiService); private readonly router=inject(Router); private readonly fb=inject(FormBuilder); private readonly destroyRef=inject(DestroyRef);
  readonly form=this.fb.nonNullable.group({providerReference:['',Validators.required],currency:['NGN',[Validators.required,Validators.pattern(/^[A-Za-z]{3}$/)]],settlementMethod:['MANUAL_BANK_TRANSFER' as ProviderPayoutSettlementMethod,Validators.required],payoutAccountReference:[''],note:['']});
  readonly eligible=signal<readonly EligibleProviderEarning[]>([]); readonly selected=signal<ReadonlySet<string>>(new Set()); readonly selectedRows=signal(new Map<string,EligibleProviderEarning>()); readonly accounts=signal<readonly AdminProviderPayoutAccount[]>([]); readonly loaded=signal(false); readonly eligibleLoading=signal(false); readonly accountsLoading=signal(false); readonly eligibleError=signal(''); readonly accountsError=signal(''); readonly createError=signal(''); readonly creating=signal(false); readonly page=signal(1); readonly totalPages=signal(0); readonly money=formatEarningMoney; readonly source=earningSourceLabel; private context='';
  constructor(){this.form.controls.providerReference.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.destinationContextChanged());this.form.controls.currency.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(()=>this.destinationContextChanged());this.form.controls.settlementMethod.valueChanges.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(v=>{this.form.controls.payoutAccountReference.setValue('',{emitEvent:false});if(v==='MANUAL_BANK_TRANSFER')this.loadAccounts()});}
  accountContextReady(){return!!this.form.controls.providerReference.value.trim()&&/^[A-Za-z]{3}$/.test(this.form.controls.currency.value)} selectedAccount(){return this.accounts().find(a=>a.reference===this.form.controls.payoutAccountReference.value)??null}
  private destinationContextChanged(){this.form.controls.payoutAccountReference.setValue('',{emitEvent:false});this.accounts.set([]);if(this.form.controls.settlementMethod.value==='MANUAL_BANK_TRANSFER')this.loadAccounts()}
  loadAccounts(){if(!this.accountContextReady())return;this.accountsLoading.set(true);this.accountsError.set('');this.accountsApi.adminList({providerReference:this.form.controls.providerReference.value.trim(),status:'VERIFIED',currency:this.form.controls.currency.value.toUpperCase(),page:1,limit:100}).pipe(finalize(()=>this.accountsLoading.set(false))).subscribe({next:r=>this.accounts.set(r.items),error:()=>this.accountsError.set('Unable to load verified accounts.')})}
  loadEligible(page:number,clear:boolean){if(this.form.invalid||page<1)return;const v=this.form.getRawValue(),context=`${v.providerReference.trim()}|${v.currency.toUpperCase()}`;if(clear||context!==this.context){this.selected.set(new Set());this.selectedRows.set(new Map());this.context=context}this.loadAccounts();this.eligibleLoading.set(true);this.eligibleError.set('');this.api.getEligibleEarnings({providerReference:v.providerReference.trim(),currency:v.currency.toUpperCase(),page,limit:25}).pipe(finalize(()=>this.eligibleLoading.set(false))).subscribe({next:r=>{this.eligible.set(r.items);this.page.set(r.page);this.totalPages.set(r.totalPages);this.loaded.set(true)},error:()=>this.eligibleError.set('Eligible earnings could not be loaded.')})}
  toggle(e:EligibleProviderEarning){const refs=new Set(this.selected()),rows=new Map(this.selectedRows());if(refs.has(e.reference)){refs.delete(e.reference);rows.delete(e.reference)}else{refs.add(e.reference);rows.set(e.reference,e)}this.selected.set(refs);this.selectedRows.set(rows)} preview(){return[...this.selectedRows().values()].reduce((sum,e)=>sum+e.providerShareMinor,0)}
  create(){if(!this.selected().size||this.creating())return;const destination=this.selectedAccount();const copy=destination?'The selected destination will be recorded as an immutable snapshot. Creating this payout does not send money.':'No payout destination will be recorded. The settlement can still be managed manually.';if(!confirm(`Create this draft payout? ${copy}`))return;const v=this.form.getRawValue();this.creating.set(true);this.createError.set('');this.api.createPayout({providerReference:v.providerReference.trim(),currency:v.currency.toUpperCase(),earningReferences:[...this.selected()],settlementMethod:v.settlementMethod,...(v.payoutAccountReference?{payoutAccountReference:v.payoutAccountReference}:{}),note:v.note.trim()||undefined}).pipe(finalize(()=>this.creating.set(false))).subscribe({next:p=>this.router.navigate(['/admin/provider-payouts',p.reference]),error:(e:HttpErrorResponse)=>{if(e.status===409&&v.payoutAccountReference){this.createError.set('The selected payout destination is no longer available. Choose another verified account or continue without a recorded destination.');this.form.controls.payoutAccountReference.setValue('',{emitEvent:false});this.loadAccounts()}else if(e.status===409)this.createError.set('One or more selected earnings are no longer available for payout. Refresh and try again.');else this.createError.set('The draft payout could not be created.')}})} date(v:string){return new Intl.DateTimeFormat('en-NG',{dateStyle:'medium'}).format(new Date(v))}
}
