import { TestBed } from '@angular/core/testing';
import { ActivatedRoute, provideRouter } from '@angular/router';
import { of } from 'rxjs';
import { RewardWithdrawalsApiService } from '../../core/services/reward-withdrawals-api.service';
import { AdminRewardWithdrawalDetailPageComponent } from './admin-reward-withdrawal-detail-page.component';

const detail = { withdrawalReference:'SCW-1',user:{displayName:'Ada',email:'ada@example.com'},points:100,amount:'1000.00',currency:'NGN',conversionRate:{points:100,amount:'1000.00'},bankName:'Access Bank',accountNumber:'0123456789',accountName:'Ada Okafor',status:'REQUESTED' as const,requestedAt:'2026-08-26T10:00:00Z',processingAt:null,paidAt:null,failedAt:null,cancelledAt:null,externalReference:null,adminNote:null,history:[{fromStatus:null,toStatus:'REQUESTED' as const,reasonCode:'WITHDRAWAL_REQUESTED',reasonNote:null,createdAt:'2026-08-26T10:00:00Z'}] };
describe('AdminRewardWithdrawalDetailPageComponent',()=>{
  it('uses a modal and requires an external reference before marking paid',async()=>{const api={adminDetail:vi.fn(()=>of(detail)),markPaid:vi.fn(()=>of(detail)),markProcessing:vi.fn(),markFailed:vi.fn(),adminCancel:vi.fn()};await TestBed.configureTestingModule({imports:[AdminRewardWithdrawalDetailPageComponent],providers:[provideRouter([]),{provide:ActivatedRoute,useValue:{snapshot:{paramMap:{get:()=> 'SCW-1'}}}},{provide:RewardWithdrawalsApiService,useValue:api}]}).compileComponents();const f=TestBed.createComponent(AdminRewardWithdrawalDetailPageComponent);f.detectChanges();f.componentInstance.open('PAID');f.detectChanges();const dialog=f.nativeElement.querySelector('[role="alertdialog"]');expect(dialog).toBeTruthy();expect(dialog.getAttribute('aria-modal')).toBe('true');expect(f.componentInstance.invalid('PAID')).toBe(true);f.componentInstance.actionForm.patchValue({externalReference:'BANK-1'});f.componentInstance.confirm();expect(api.markPaid).toHaveBeenCalledWith('SCW-1','BANK-1',undefined)});
  it('shows no mutation actions for a paid withdrawal',async()=>{const api={adminDetail:()=>of({...detail,status:'PAID'}),markPaid:vi.fn(),markProcessing:vi.fn(),markFailed:vi.fn(),adminCancel:vi.fn()};await TestBed.configureTestingModule({imports:[AdminRewardWithdrawalDetailPageComponent],providers:[provideRouter([]),{provide:ActivatedRoute,useValue:{snapshot:{paramMap:{get:()=> 'SCW-1'}}}},{provide:RewardWithdrawalsApiService,useValue:api}]}).compileComponents();const f=TestBed.createComponent(AdminRewardWithdrawalDetailPageComponent);f.detectChanges();expect(f.nativeElement.textContent).not.toContain('Mark processing');expect(f.nativeElement.textContent).not.toContain('Mark failed')});
});
